// Code generated by protoc-gen-go.
// source: ballerRelation.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GamerSendBallerRelationsDataS2C_MsgID int32

const (
	GamerSendBallerRelationsDataS2C_eMsgID GamerSendBallerRelationsDataS2C_MsgID = 9217
)

var GamerSendBallerRelationsDataS2C_MsgID_name = map[int32]string{
	9217: "eMsgID",
}
var GamerSendBallerRelationsDataS2C_MsgID_value = map[string]int32{
	"eMsgID": 9217,
}

func (x GamerSendBallerRelationsDataS2C_MsgID) Enum() *GamerSendBallerRelationsDataS2C_MsgID {
	p := new(GamerSendBallerRelationsDataS2C_MsgID)
	*p = x
	return p
}
func (x GamerSendBallerRelationsDataS2C_MsgID) String() string {
	return proto.EnumName(GamerSendBallerRelationsDataS2C_MsgID_name, int32(x))
}
func (x *GamerSendBallerRelationsDataS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerSendBallerRelationsDataS2C_MsgID_value, data, "GamerSendBallerRelationsDataS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerSendBallerRelationsDataS2C_MsgID(value)
	return nil
}
func (GamerSendBallerRelationsDataS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor7, []int{2, 0}
}

type PlayerRelationEnhanceC2S_MsgID int32

const (
	PlayerRelationEnhanceC2S_eMsgID PlayerRelationEnhanceC2S_MsgID = 9218
)

var PlayerRelationEnhanceC2S_MsgID_name = map[int32]string{
	9218: "eMsgID",
}
var PlayerRelationEnhanceC2S_MsgID_value = map[string]int32{
	"eMsgID": 9218,
}

func (x PlayerRelationEnhanceC2S_MsgID) Enum() *PlayerRelationEnhanceC2S_MsgID {
	p := new(PlayerRelationEnhanceC2S_MsgID)
	*p = x
	return p
}
func (x PlayerRelationEnhanceC2S_MsgID) String() string {
	return proto.EnumName(PlayerRelationEnhanceC2S_MsgID_name, int32(x))
}
func (x *PlayerRelationEnhanceC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PlayerRelationEnhanceC2S_MsgID_value, data, "PlayerRelationEnhanceC2S_MsgID")
	if err != nil {
		return err
	}
	*x = PlayerRelationEnhanceC2S_MsgID(value)
	return nil
}
func (PlayerRelationEnhanceC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor7, []int{3, 0}
}

type PlayerRelationEnhanceS2C_MsgID int32

const (
	PlayerRelationEnhanceS2C_eMsgID PlayerRelationEnhanceS2C_MsgID = 9218
)

var PlayerRelationEnhanceS2C_MsgID_name = map[int32]string{
	9218: "eMsgID",
}
var PlayerRelationEnhanceS2C_MsgID_value = map[string]int32{
	"eMsgID": 9218,
}

func (x PlayerRelationEnhanceS2C_MsgID) Enum() *PlayerRelationEnhanceS2C_MsgID {
	p := new(PlayerRelationEnhanceS2C_MsgID)
	*p = x
	return p
}
func (x PlayerRelationEnhanceS2C_MsgID) String() string {
	return proto.EnumName(PlayerRelationEnhanceS2C_MsgID_name, int32(x))
}
func (x *PlayerRelationEnhanceS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PlayerRelationEnhanceS2C_MsgID_value, data, "PlayerRelationEnhanceS2C_MsgID")
	if err != nil {
		return err
	}
	*x = PlayerRelationEnhanceS2C_MsgID(value)
	return nil
}
func (PlayerRelationEnhanceS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor7, []int{4, 0}
}

// --------------------------------以下是球员羁绊---------------------------------
// 球员羁绊数据
type BallerRelationData struct {
	Id               *int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Level            *int32 `protobuf:"varint,2,opt,name=Level" json:"Level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BallerRelationData) Reset()                    { *m = BallerRelationData{} }
func (m *BallerRelationData) String() string            { return proto.CompactTextString(m) }
func (*BallerRelationData) ProtoMessage()               {}
func (*BallerRelationData) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *BallerRelationData) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BallerRelationData) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

// 个人球员羁绊信息
type BallerRelationInfo struct {
	BallerRelations  []*BallerRelationData `protobuf:"bytes,1,rep,name=BallerRelations" json:"BallerRelations,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *BallerRelationInfo) Reset()                    { *m = BallerRelationInfo{} }
func (m *BallerRelationInfo) String() string            { return proto.CompactTextString(m) }
func (*BallerRelationInfo) ProtoMessage()               {}
func (*BallerRelationInfo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *BallerRelationInfo) GetBallerRelations() []*BallerRelationData {
	if m != nil {
		return m.BallerRelations
	}
	return nil
}

// 推送所有球员羁绊数据
type GamerSendBallerRelationsDataS2C struct {
	// 所有球员羁绊数据
	BallerRelations  []*BallerRelationData `protobuf:"bytes,1,rep,name=BallerRelations" json:"BallerRelations,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GamerSendBallerRelationsDataS2C) Reset()         { *m = GamerSendBallerRelationsDataS2C{} }
func (m *GamerSendBallerRelationsDataS2C) String() string { return proto.CompactTextString(m) }
func (*GamerSendBallerRelationsDataS2C) ProtoMessage()    {}
func (*GamerSendBallerRelationsDataS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{2}
}

func (m *GamerSendBallerRelationsDataS2C) GetBallerRelations() []*BallerRelationData {
	if m != nil {
		return m.BallerRelations
	}
	return nil
}

// 请求解锁/强化/突破球员羁绊
type PlayerRelationEnhanceC2S struct {
	// 球员id
	PlayerId *int32 `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	// 羁绊id
	PlayerRelationId *int32 `protobuf:"varint,2,opt,name=playerRelationId" json:"playerRelationId,omitempty"`
	// 新手引导id
	GuideId          *int32 `protobuf:"varint,3,opt,name=guideId" json:"guideId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerRelationEnhanceC2S) Reset()                    { *m = PlayerRelationEnhanceC2S{} }
func (m *PlayerRelationEnhanceC2S) String() string            { return proto.CompactTextString(m) }
func (*PlayerRelationEnhanceC2S) ProtoMessage()               {}
func (*PlayerRelationEnhanceC2S) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *PlayerRelationEnhanceC2S) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerRelationEnhanceC2S) GetPlayerRelationId() int32 {
	if m != nil && m.PlayerRelationId != nil {
		return *m.PlayerRelationId
	}
	return 0
}

func (m *PlayerRelationEnhanceC2S) GetGuideId() int32 {
	if m != nil && m.GuideId != nil {
		return *m.GuideId
	}
	return 0
}

// 请求解锁/强化/突破球员羁绊
type PlayerRelationEnhanceS2C struct {
	// 被解锁/强化/突破的球员羁绊信息
	BallerRelation   *BallerRelationData `protobuf:"bytes,1,opt,name=BallerRelation" json:"BallerRelation,omitempty"`
	PlayerId         *int32              `protobuf:"varint,2,opt,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PlayerRelationEnhanceS2C) Reset()                    { *m = PlayerRelationEnhanceS2C{} }
func (m *PlayerRelationEnhanceS2C) String() string            { return proto.CompactTextString(m) }
func (*PlayerRelationEnhanceS2C) ProtoMessage()               {}
func (*PlayerRelationEnhanceS2C) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *PlayerRelationEnhanceS2C) GetBallerRelation() *BallerRelationData {
	if m != nil {
		return m.BallerRelation
	}
	return nil
}

func (m *PlayerRelationEnhanceS2C) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func init() {
	proto.RegisterType((*BallerRelationData)(nil), "BallerRelationData")
	proto.RegisterType((*BallerRelationInfo)(nil), "BallerRelationInfo")
	proto.RegisterType((*GamerSendBallerRelationsDataS2C)(nil), "GamerSendBallerRelationsDataS2C")
	proto.RegisterType((*PlayerRelationEnhanceC2S)(nil), "PlayerRelationEnhanceC2S")
	proto.RegisterType((*PlayerRelationEnhanceS2C)(nil), "PlayerRelationEnhanceS2C")
	proto.RegisterEnum("GamerSendBallerRelationsDataS2C_MsgID", GamerSendBallerRelationsDataS2C_MsgID_name, GamerSendBallerRelationsDataS2C_MsgID_value)
	proto.RegisterEnum("PlayerRelationEnhanceC2S_MsgID", PlayerRelationEnhanceC2S_MsgID_name, PlayerRelationEnhanceC2S_MsgID_value)
	proto.RegisterEnum("PlayerRelationEnhanceS2C_MsgID", PlayerRelationEnhanceS2C_MsgID_name, PlayerRelationEnhanceS2C_MsgID_value)
}

func init() { proto.RegisterFile("ballerRelation.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x4a, 0xcc, 0xc9,
	0x49, 0x2d, 0x0a, 0x4a, 0xcd, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x97, 0xe2, 0x4a, 0xce, 0xcf, 0x4b, 0x83, 0xb0, 0x95, 0xf4, 0xb9, 0x84, 0x9c, 0x50, 0xd4, 0xb8,
	0x24, 0x96, 0x24, 0x0a, 0x71, 0x71, 0x31, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x0a,
	0xf1, 0x72, 0xb1, 0xfa, 0xa4, 0x96, 0xa5, 0xe6, 0x48, 0x30, 0x81, 0xb8, 0x4a, 0x4e, 0xe8, 0x1a,
	0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0x74, 0xb8, 0xf8, 0x51, 0x45, 0x8b, 0x81, 0xba, 0x99, 0x35, 0xb8,
	0x8d, 0x84, 0xf5, 0x30, 0x8d, 0x57, 0x4a, 0xe5, 0x92, 0x77, 0x4f, 0xcc, 0x4d, 0x2d, 0x0a, 0x4e,
	0xcd, 0x4b, 0x41, 0xd3, 0x06, 0x92, 0x0f, 0x36, 0x72, 0x26, 0xd1, 0x40, 0x11, 0x2e, 0x56, 0xdf,
	0xe2, 0x74, 0x4f, 0x17, 0x21, 0x6e, 0x2e, 0xb6, 0x54, 0x30, 0x4b, 0xa0, 0xd1, 0x43, 0x29, 0x97,
	0x4b, 0x22, 0x20, 0x27, 0xb1, 0x12, 0xa1, 0xd6, 0x35, 0x2f, 0x23, 0x31, 0x2f, 0x39, 0xd5, 0xd9,
	0x28, 0x58, 0x48, 0x80, 0x8b, 0xa3, 0x00, 0x2c, 0x07, 0xf7, 0xa7, 0x04, 0x97, 0x40, 0x01, 0x8a,
	0x6a, 0xa0, 0x0c, 0xd8, 0xcb, 0x42, 0xfc, 0x5c, 0xec, 0xe9, 0xa5, 0x99, 0x29, 0xa9, 0x40, 0x01,
	0x66, 0x70, 0x18, 0x60, 0xb1, 0xae, 0xc9, 0x43, 0x29, 0x1f, 0x87, 0x75, 0x20, 0xef, 0x68, 0x73,
	0xf1, 0xa1, 0x3a, 0x1b, 0x6c, 0x29, 0x76, 0xdf, 0xa0, 0xb8, 0x8d, 0x09, 0xb7, 0x85, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xae, 0x91, 0x5e, 0x20, 0xde, 0x01, 0x00, 0x00,
}
