// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GamerSendChatInfoC2S_MsgID int32

const (
	GamerSendChatInfoC2S_eMsgID GamerSendChatInfoC2S_MsgID = 1550
)

var GamerSendChatInfoC2S_MsgID_name = map[int32]string{
	1550: "eMsgID",
}
var GamerSendChatInfoC2S_MsgID_value = map[string]int32{
	"eMsgID": 1550,
}

func (x GamerSendChatInfoC2S_MsgID) Enum() *GamerSendChatInfoC2S_MsgID {
	p := new(GamerSendChatInfoC2S_MsgID)
	*p = x
	return p
}
func (x GamerSendChatInfoC2S_MsgID) String() string {
	return proto.EnumName(GamerSendChatInfoC2S_MsgID_name, int32(x))
}
func (x *GamerSendChatInfoC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerSendChatInfoC2S_MsgID_value, data, "GamerSendChatInfoC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerSendChatInfoC2S_MsgID(value)
	return nil
}
func (GamerSendChatInfoC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{0, 0}
}

type GamerSendChatInfoS2C_MsgID int32

const (
	GamerSendChatInfoS2C_eMsgID GamerSendChatInfoS2C_MsgID = 1550
)

var GamerSendChatInfoS2C_MsgID_name = map[int32]string{
	1550: "eMsgID",
}
var GamerSendChatInfoS2C_MsgID_value = map[string]int32{
	"eMsgID": 1550,
}

func (x GamerSendChatInfoS2C_MsgID) Enum() *GamerSendChatInfoS2C_MsgID {
	p := new(GamerSendChatInfoS2C_MsgID)
	*p = x
	return p
}
func (x GamerSendChatInfoS2C_MsgID) String() string {
	return proto.EnumName(GamerSendChatInfoS2C_MsgID_name, int32(x))
}
func (x *GamerSendChatInfoS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerSendChatInfoS2C_MsgID_value, data, "GamerSendChatInfoS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerSendChatInfoS2C_MsgID(value)
	return nil
}
func (GamerSendChatInfoS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{1, 0}
}

type GamerReceiveChatInfoS2C_MsgID int32

const (
	GamerReceiveChatInfoS2C_eMsgID GamerReceiveChatInfoS2C_MsgID = 1551
)

var GamerReceiveChatInfoS2C_MsgID_name = map[int32]string{
	1551: "eMsgID",
}
var GamerReceiveChatInfoS2C_MsgID_value = map[string]int32{
	"eMsgID": 1551,
}

func (x GamerReceiveChatInfoS2C_MsgID) Enum() *GamerReceiveChatInfoS2C_MsgID {
	p := new(GamerReceiveChatInfoS2C_MsgID)
	*p = x
	return p
}
func (x GamerReceiveChatInfoS2C_MsgID) String() string {
	return proto.EnumName(GamerReceiveChatInfoS2C_MsgID_name, int32(x))
}
func (x *GamerReceiveChatInfoS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerReceiveChatInfoS2C_MsgID_value, data, "GamerReceiveChatInfoS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerReceiveChatInfoS2C_MsgID(value)
	return nil
}
func (GamerReceiveChatInfoS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{2, 0}
}

type GamerGetPrivateChatC2S_MsgID int32

const (
	GamerGetPrivateChatC2S_eMsgID GamerGetPrivateChatC2S_MsgID = 1552
)

var GamerGetPrivateChatC2S_MsgID_name = map[int32]string{
	1552: "eMsgID",
}
var GamerGetPrivateChatC2S_MsgID_value = map[string]int32{
	"eMsgID": 1552,
}

func (x GamerGetPrivateChatC2S_MsgID) Enum() *GamerGetPrivateChatC2S_MsgID {
	p := new(GamerGetPrivateChatC2S_MsgID)
	*p = x
	return p
}
func (x GamerGetPrivateChatC2S_MsgID) String() string {
	return proto.EnumName(GamerGetPrivateChatC2S_MsgID_name, int32(x))
}
func (x *GamerGetPrivateChatC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerGetPrivateChatC2S_MsgID_value, data, "GamerGetPrivateChatC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerGetPrivateChatC2S_MsgID(value)
	return nil
}
func (GamerGetPrivateChatC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{3, 0}
}

type GamerGetPrivateChatS2C_MsgID int32

const (
	GamerGetPrivateChatS2C_eMsgID GamerGetPrivateChatS2C_MsgID = 1552
)

var GamerGetPrivateChatS2C_MsgID_name = map[int32]string{
	1552: "eMsgID",
}
var GamerGetPrivateChatS2C_MsgID_value = map[string]int32{
	"eMsgID": 1552,
}

func (x GamerGetPrivateChatS2C_MsgID) Enum() *GamerGetPrivateChatS2C_MsgID {
	p := new(GamerGetPrivateChatS2C_MsgID)
	*p = x
	return p
}
func (x GamerGetPrivateChatS2C_MsgID) String() string {
	return proto.EnumName(GamerGetPrivateChatS2C_MsgID_name, int32(x))
}
func (x *GamerGetPrivateChatS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerGetPrivateChatS2C_MsgID_value, data, "GamerGetPrivateChatS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerGetPrivateChatS2C_MsgID(value)
	return nil
}
func (GamerGetPrivateChatS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{4, 0}
}

type GamerDelPrivateChatC2S_MsgID int32

const (
	GamerDelPrivateChatC2S_eMsgID GamerDelPrivateChatC2S_MsgID = 1553
)

var GamerDelPrivateChatC2S_MsgID_name = map[int32]string{
	1553: "eMsgID",
}
var GamerDelPrivateChatC2S_MsgID_value = map[string]int32{
	"eMsgID": 1553,
}

func (x GamerDelPrivateChatC2S_MsgID) Enum() *GamerDelPrivateChatC2S_MsgID {
	p := new(GamerDelPrivateChatC2S_MsgID)
	*p = x
	return p
}
func (x GamerDelPrivateChatC2S_MsgID) String() string {
	return proto.EnumName(GamerDelPrivateChatC2S_MsgID_name, int32(x))
}
func (x *GamerDelPrivateChatC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDelPrivateChatC2S_MsgID_value, data, "GamerDelPrivateChatC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDelPrivateChatC2S_MsgID(value)
	return nil
}
func (GamerDelPrivateChatC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{5, 0}
}

type GamerDelPrivateChatS2C_MsgID int32

const (
	GamerDelPrivateChatS2C_eMsgID GamerDelPrivateChatS2C_MsgID = 1553
)

var GamerDelPrivateChatS2C_MsgID_name = map[int32]string{
	1553: "eMsgID",
}
var GamerDelPrivateChatS2C_MsgID_value = map[string]int32{
	"eMsgID": 1553,
}

func (x GamerDelPrivateChatS2C_MsgID) Enum() *GamerDelPrivateChatS2C_MsgID {
	p := new(GamerDelPrivateChatS2C_MsgID)
	*p = x
	return p
}
func (x GamerDelPrivateChatS2C_MsgID) String() string {
	return proto.EnumName(GamerDelPrivateChatS2C_MsgID_name, int32(x))
}
func (x *GamerDelPrivateChatS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDelPrivateChatS2C_MsgID_value, data, "GamerDelPrivateChatS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDelPrivateChatS2C_MsgID(value)
	return nil
}
func (GamerDelPrivateChatS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{6, 0}
}

type GamerReadChatC2S_MsgID int32

const (
	GamerReadChatC2S_eMsgID GamerReadChatC2S_MsgID = 1554
)

var GamerReadChatC2S_MsgID_name = map[int32]string{
	1554: "eMsgID",
}
var GamerReadChatC2S_MsgID_value = map[string]int32{
	"eMsgID": 1554,
}

func (x GamerReadChatC2S_MsgID) Enum() *GamerReadChatC2S_MsgID {
	p := new(GamerReadChatC2S_MsgID)
	*p = x
	return p
}
func (x GamerReadChatC2S_MsgID) String() string {
	return proto.EnumName(GamerReadChatC2S_MsgID_name, int32(x))
}
func (x *GamerReadChatC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerReadChatC2S_MsgID_value, data, "GamerReadChatC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerReadChatC2S_MsgID(value)
	return nil
}
func (GamerReadChatC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{7, 0} }

type GamerReadChatS2C_MsgID int32

const (
	GamerReadChatS2C_eMsgID GamerReadChatS2C_MsgID = 1554
)

var GamerReadChatS2C_MsgID_name = map[int32]string{
	1554: "eMsgID",
}
var GamerReadChatS2C_MsgID_value = map[string]int32{
	"eMsgID": 1554,
}

func (x GamerReadChatS2C_MsgID) Enum() *GamerReadChatS2C_MsgID {
	p := new(GamerReadChatS2C_MsgID)
	*p = x
	return p
}
func (x GamerReadChatS2C_MsgID) String() string {
	return proto.EnumName(GamerReadChatS2C_MsgID_name, int32(x))
}
func (x *GamerReadChatS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerReadChatS2C_MsgID_value, data, "GamerReadChatS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerReadChatS2C_MsgID(value)
	return nil
}
func (GamerReadChatS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{8, 0} }

type GamerBroadcastRarePlayerS2C_MsgID int32

const (
	GamerBroadcastRarePlayerS2C_eMsgID GamerBroadcastRarePlayerS2C_MsgID = 1555
)

var GamerBroadcastRarePlayerS2C_MsgID_name = map[int32]string{
	1555: "eMsgID",
}
var GamerBroadcastRarePlayerS2C_MsgID_value = map[string]int32{
	"eMsgID": 1555,
}

func (x GamerBroadcastRarePlayerS2C_MsgID) Enum() *GamerBroadcastRarePlayerS2C_MsgID {
	p := new(GamerBroadcastRarePlayerS2C_MsgID)
	*p = x
	return p
}
func (x GamerBroadcastRarePlayerS2C_MsgID) String() string {
	return proto.EnumName(GamerBroadcastRarePlayerS2C_MsgID_name, int32(x))
}
func (x *GamerBroadcastRarePlayerS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerBroadcastRarePlayerS2C_MsgID_value, data, "GamerBroadcastRarePlayerS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerBroadcastRarePlayerS2C_MsgID(value)
	return nil
}
func (GamerBroadcastRarePlayerS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{10, 0}
}

type GamerConfirmBroadcastC2S_MsgID int32

const (
	GamerConfirmBroadcastC2S_eMsgID GamerConfirmBroadcastC2S_MsgID = 1556
)

var GamerConfirmBroadcastC2S_MsgID_name = map[int32]string{
	1556: "eMsgID",
}
var GamerConfirmBroadcastC2S_MsgID_value = map[string]int32{
	"eMsgID": 1556,
}

func (x GamerConfirmBroadcastC2S_MsgID) Enum() *GamerConfirmBroadcastC2S_MsgID {
	p := new(GamerConfirmBroadcastC2S_MsgID)
	*p = x
	return p
}
func (x GamerConfirmBroadcastC2S_MsgID) String() string {
	return proto.EnumName(GamerConfirmBroadcastC2S_MsgID_name, int32(x))
}
func (x *GamerConfirmBroadcastC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerConfirmBroadcastC2S_MsgID_value, data, "GamerConfirmBroadcastC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerConfirmBroadcastC2S_MsgID(value)
	return nil
}
func (GamerConfirmBroadcastC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{13, 0}
}

type SystemBroadcastC2S_MsgID int32

const (
	SystemBroadcastC2S_eMsgID SystemBroadcastC2S_MsgID = 1558
)

var SystemBroadcastC2S_MsgID_name = map[int32]string{
	1558: "eMsgID",
}
var SystemBroadcastC2S_MsgID_value = map[string]int32{
	"eMsgID": 1558,
}

func (x SystemBroadcastC2S_MsgID) Enum() *SystemBroadcastC2S_MsgID {
	p := new(SystemBroadcastC2S_MsgID)
	*p = x
	return p
}
func (x SystemBroadcastC2S_MsgID) String() string {
	return proto.EnumName(SystemBroadcastC2S_MsgID_name, int32(x))
}
func (x *SystemBroadcastC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SystemBroadcastC2S_MsgID_value, data, "SystemBroadcastC2S_MsgID")
	if err != nil {
		return err
	}
	*x = SystemBroadcastC2S_MsgID(value)
	return nil
}
func (SystemBroadcastC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{14, 0}
}

type SystemBroadcastS2C_MsgID int32

const (
	SystemBroadcastS2C_eMsgID SystemBroadcastS2C_MsgID = 1558
)

var SystemBroadcastS2C_MsgID_name = map[int32]string{
	1558: "eMsgID",
}
var SystemBroadcastS2C_MsgID_value = map[string]int32{
	"eMsgID": 1558,
}

func (x SystemBroadcastS2C_MsgID) Enum() *SystemBroadcastS2C_MsgID {
	p := new(SystemBroadcastS2C_MsgID)
	*p = x
	return p
}
func (x SystemBroadcastS2C_MsgID) String() string {
	return proto.EnumName(SystemBroadcastS2C_MsgID_name, int32(x))
}
func (x *SystemBroadcastS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SystemBroadcastS2C_MsgID_value, data, "SystemBroadcastS2C_MsgID")
	if err != nil {
		return err
	}
	*x = SystemBroadcastS2C_MsgID(value)
	return nil
}
func (SystemBroadcastS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{15, 0}
}

// 发送消息
type GamerSendChatInfoC2S struct {
	// 聊天频道
	ChatChannelType *ChatChannel `protobuf:"varint,1,opt,name=chatChannelType,enum=ChatChannel" json:"chatChannelType,omitempty"`
	// 信息类型(1:文字，2:语音,3:交易邀请,4:联盟交易, 5:商业邀请赛组队邀请)
	ChatType *int32 `protobuf:"varint,2,opt,name=chatType" json:"chatType,omitempty"`
	// 信息内容
	ChatInfo []byte `protobuf:"bytes,3,opt,name=chatInfo" json:"chatInfo,omitempty"`
	// 私聊对象
	RecvId           *int32 `protobuf:"varint,4,opt,name=recvId" json:"recvId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerSendChatInfoC2S) Reset()                    { *m = GamerSendChatInfoC2S{} }
func (m *GamerSendChatInfoC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerSendChatInfoC2S) ProtoMessage()               {}
func (*GamerSendChatInfoC2S) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *GamerSendChatInfoC2S) GetChatChannelType() ChatChannel {
	if m != nil && m.ChatChannelType != nil {
		return *m.ChatChannelType
	}
	return ChatChannel_world
}

func (m *GamerSendChatInfoC2S) GetChatType() int32 {
	if m != nil && m.ChatType != nil {
		return *m.ChatType
	}
	return 0
}

func (m *GamerSendChatInfoC2S) GetChatInfo() []byte {
	if m != nil {
		return m.ChatInfo
	}
	return nil
}

func (m *GamerSendChatInfoC2S) GetRecvId() int32 {
	if m != nil && m.RecvId != nil {
		return *m.RecvId
	}
	return 0
}

// 发送消息
type GamerSendChatInfoS2C struct {
	// 信息类型(1:文字，2:语音,3:交易邀请,4:联盟交易, 5:商业邀请赛组队邀请)
	ChatType *int32 `protobuf:"varint,1,opt,name=chatType" json:"chatType,omitempty"`
	// 信息内容
	ChatInfo []byte `protobuf:"bytes,2,opt,name=chatInfo" json:"chatInfo,omitempty"`
	// 发送时间
	SendTime *int64 `protobuf:"varint,3,opt,name=sendTime" json:"sendTime,omitempty"`
	// 聊天频道
	ChatChannelType *ChatChannel `protobuf:"varint,4,opt,name=chatChannelType,enum=ChatChannel" json:"chatChannelType,omitempty"`
	// 私聊对象
	RecvId           *int32 `protobuf:"varint,5,opt,name=recvId" json:"recvId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerSendChatInfoS2C) Reset()                    { *m = GamerSendChatInfoS2C{} }
func (m *GamerSendChatInfoS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerSendChatInfoS2C) ProtoMessage()               {}
func (*GamerSendChatInfoS2C) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *GamerSendChatInfoS2C) GetChatType() int32 {
	if m != nil && m.ChatType != nil {
		return *m.ChatType
	}
	return 0
}

func (m *GamerSendChatInfoS2C) GetChatInfo() []byte {
	if m != nil {
		return m.ChatInfo
	}
	return nil
}

func (m *GamerSendChatInfoS2C) GetSendTime() int64 {
	if m != nil && m.SendTime != nil {
		return *m.SendTime
	}
	return 0
}

func (m *GamerSendChatInfoS2C) GetChatChannelType() ChatChannel {
	if m != nil && m.ChatChannelType != nil {
		return *m.ChatChannelType
	}
	return ChatChannel_world
}

func (m *GamerSendChatInfoS2C) GetRecvId() int32 {
	if m != nil && m.RecvId != nil {
		return *m.RecvId
	}
	return 0
}

// 接收消息
type GamerReceiveChatInfoS2C struct {
	// 聊天频道
	ChatChannelType *ChatChannel `protobuf:"varint,1,opt,name=chatChannelType,enum=ChatChannel" json:"chatChannelType,omitempty"`
	// 聊天内容
	ChatLog          *ChatLog `protobuf:"bytes,2,opt,name=chatLog" json:"chatLog,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GamerReceiveChatInfoS2C) Reset()                    { *m = GamerReceiveChatInfoS2C{} }
func (m *GamerReceiveChatInfoS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerReceiveChatInfoS2C) ProtoMessage()               {}
func (*GamerReceiveChatInfoS2C) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *GamerReceiveChatInfoS2C) GetChatChannelType() ChatChannel {
	if m != nil && m.ChatChannelType != nil {
		return *m.ChatChannelType
	}
	return ChatChannel_world
}

func (m *GamerReceiveChatInfoS2C) GetChatLog() *ChatLog {
	if m != nil {
		return m.ChatLog
	}
	return nil
}

// 获取私聊信息
type GamerGetPrivateChatC2S struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerGetPrivateChatC2S) Reset()                    { *m = GamerGetPrivateChatC2S{} }
func (m *GamerGetPrivateChatC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerGetPrivateChatC2S) ProtoMessage()               {}
func (*GamerGetPrivateChatC2S) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

// 获取私聊信息
type GamerGetPrivateChatS2C struct {
	// 私聊消息
	ChatLogs         []*ChatLog `protobuf:"bytes,1,rep,name=chatLogs" json:"chatLogs,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *GamerGetPrivateChatS2C) Reset()                    { *m = GamerGetPrivateChatS2C{} }
func (m *GamerGetPrivateChatS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerGetPrivateChatS2C) ProtoMessage()               {}
func (*GamerGetPrivateChatS2C) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

func (m *GamerGetPrivateChatS2C) GetChatLogs() []*ChatLog {
	if m != nil {
		return m.ChatLogs
	}
	return nil
}

// 清空记录
type GamerDelPrivateChatC2S struct {
	// 玩家ID
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelPrivateChatC2S) Reset()                    { *m = GamerDelPrivateChatC2S{} }
func (m *GamerDelPrivateChatC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerDelPrivateChatC2S) ProtoMessage()               {}
func (*GamerDelPrivateChatC2S) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

func (m *GamerDelPrivateChatC2S) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

// 清空记录
type GamerDelPrivateChatS2C struct {
	// 玩家ID
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelPrivateChatS2C) Reset()                    { *m = GamerDelPrivateChatS2C{} }
func (m *GamerDelPrivateChatS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDelPrivateChatS2C) ProtoMessage()               {}
func (*GamerDelPrivateChatS2C) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{6} }

func (m *GamerDelPrivateChatS2C) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

// 已读回执
type GamerReadChatC2S struct {
	// 玩家ID
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerReadChatC2S) Reset()                    { *m = GamerReadChatC2S{} }
func (m *GamerReadChatC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerReadChatC2S) ProtoMessage()               {}
func (*GamerReadChatC2S) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{7} }

func (m *GamerReadChatC2S) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

// 已读回执
type GamerReadChatS2C struct {
	// 是否已处理已读回执
	Processed        *bool  `protobuf:"varint,1,opt,name=processed" json:"processed,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerReadChatS2C) Reset()                    { *m = GamerReadChatS2C{} }
func (m *GamerReadChatS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerReadChatS2C) ProtoMessage()               {}
func (*GamerReadChatS2C) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{8} }

func (m *GamerReadChatS2C) GetProcessed() bool {
	if m != nil && m.Processed != nil {
		return *m.Processed
	}
	return false
}

// 聊天信息
type SendChatInfoToMatchL2M struct {
	// // 聊天频道
	ChatChannelType *ChatChannel `protobuf:"varint,1,opt,name=chatChannelType,enum=ChatChannel" json:"chatChannelType,omitempty"`
	ChatLog         *ChatLog     `protobuf:"bytes,2,opt,name=chatLog" json:"chatLog,omitempty"`
	// 发送方区服ID
	ZoneId *int32 `protobuf:"varint,4,opt,name=zoneId" json:"zoneId,omitempty"`
	// 发送方逻辑服ID
	SendLogicId *int32 `protobuf:"varint,5,opt,name=sendLogicId" json:"sendLogicId,omitempty"`
	// 联盟ID
	AlliancePlayerList []int32 `protobuf:"varint,6,rep,name=alliancePlayerList" json:"alliancePlayerList,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *SendChatInfoToMatchL2M) Reset()                    { *m = SendChatInfoToMatchL2M{} }
func (m *SendChatInfoToMatchL2M) String() string            { return proto.CompactTextString(m) }
func (*SendChatInfoToMatchL2M) ProtoMessage()               {}
func (*SendChatInfoToMatchL2M) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{9} }

func (m *SendChatInfoToMatchL2M) GetChatChannelType() ChatChannel {
	if m != nil && m.ChatChannelType != nil {
		return *m.ChatChannelType
	}
	return ChatChannel_world
}

func (m *SendChatInfoToMatchL2M) GetChatLog() *ChatLog {
	if m != nil {
		return m.ChatLog
	}
	return nil
}

func (m *SendChatInfoToMatchL2M) GetZoneId() int32 {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return 0
}

func (m *SendChatInfoToMatchL2M) GetSendLogicId() int32 {
	if m != nil && m.SendLogicId != nil {
		return *m.SendLogicId
	}
	return 0
}

func (m *SendChatInfoToMatchL2M) GetAlliancePlayerList() []int32 {
	if m != nil {
		return m.AlliancePlayerList
	}
	return nil
}

// 珍稀球员广播跑马灯
type GamerBroadcastRarePlayerS2C struct {
	// 参数类型（1：球员，2：赛季）
	Type *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	// 参数id
	ParamId *int32 `protobuf:"varint,2,opt,name=paramId" json:"paramId,omitempty"`
	// 系统配置表id
	ConfId *int32 `protobuf:"varint,3,opt,name=confId" json:"confId,omitempty"`
	// 这位欧洲人的昵称
	Name             *string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerBroadcastRarePlayerS2C) Reset()                    { *m = GamerBroadcastRarePlayerS2C{} }
func (m *GamerBroadcastRarePlayerS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerBroadcastRarePlayerS2C) ProtoMessage()               {}
func (*GamerBroadcastRarePlayerS2C) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{10} }

func (m *GamerBroadcastRarePlayerS2C) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *GamerBroadcastRarePlayerS2C) GetParamId() int32 {
	if m != nil && m.ParamId != nil {
		return *m.ParamId
	}
	return 0
}

func (m *GamerBroadcastRarePlayerS2C) GetConfId() int32 {
	if m != nil && m.ConfId != nil {
		return *m.ConfId
	}
	return 0
}

func (m *GamerBroadcastRarePlayerS2C) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type NotifyGamerBroadcastRarePlayer struct {
	// 参数类型（1：球员，2：赛季）
	Type *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	// 参数id
	ParamId *int32 `protobuf:"varint,2,opt,name=paramId" json:"paramId,omitempty"`
	// 系统配置表id
	ConfId *int32 `protobuf:"varint,3,opt,name=confId" json:"confId,omitempty"`
	// 这位欧洲人的昵称
	Name *string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	// 区服
	LsId             *int32 `protobuf:"varint,5,opt,name=lsId" json:"lsId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyGamerBroadcastRarePlayer) Reset()         { *m = NotifyGamerBroadcastRarePlayer{} }
func (m *NotifyGamerBroadcastRarePlayer) String() string { return proto.CompactTextString(m) }
func (*NotifyGamerBroadcastRarePlayer) ProtoMessage()    {}
func (*NotifyGamerBroadcastRarePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{11}
}

func (m *NotifyGamerBroadcastRarePlayer) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *NotifyGamerBroadcastRarePlayer) GetParamId() int32 {
	if m != nil && m.ParamId != nil {
		return *m.ParamId
	}
	return 0
}

func (m *NotifyGamerBroadcastRarePlayer) GetConfId() int32 {
	if m != nil && m.ConfId != nil {
		return *m.ConfId
	}
	return 0
}

func (m *NotifyGamerBroadcastRarePlayer) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NotifyGamerBroadcastRarePlayer) GetLsId() int32 {
	if m != nil && m.LsId != nil {
		return *m.LsId
	}
	return 0
}

type SystemBroadcast struct {
	// 播放优先级 数值越大优先级越高
	Index *int32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	// 播放次数 0无限次数
	Times *int32 `protobuf:"varint,2,opt,name=times" json:"times,omitempty"`
	// 渠道ID 0未知 1Android 2IOS
	Channel *string `protobuf:"bytes,3,opt,name=channel" json:"channel,omitempty"`
	// 播放间隔时间 秒
	Interval *int32 `protobuf:"varint,4,opt,name=interval" json:"interval,omitempty"`
	// 播放开始时间 0无时间限制
	BeginTime *int64 `protobuf:"varint,5,opt,name=begin_time" json:"begin_time,omitempty"`
	// 播放结束时间  0无时间限制
	EndTime *int64 `protobuf:"varint,6,opt,name=end_time" json:"end_time,omitempty"`
	// 跑马灯内容
	Content          *string `protobuf:"bytes,7,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SystemBroadcast) Reset()                    { *m = SystemBroadcast{} }
func (m *SystemBroadcast) String() string            { return proto.CompactTextString(m) }
func (*SystemBroadcast) ProtoMessage()               {}
func (*SystemBroadcast) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{12} }

func (m *SystemBroadcast) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *SystemBroadcast) GetTimes() int32 {
	if m != nil && m.Times != nil {
		return *m.Times
	}
	return 0
}

func (m *SystemBroadcast) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *SystemBroadcast) GetInterval() int32 {
	if m != nil && m.Interval != nil {
		return *m.Interval
	}
	return 0
}

func (m *SystemBroadcast) GetBeginTime() int64 {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return 0
}

func (m *SystemBroadcast) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *SystemBroadcast) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

// 客户端确认发送跑马灯消息(用于抽卡防止剧透)
type GamerConfirmBroadcastC2S struct {
	// 球员id
	PlayerId *int32 `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	// 系统配置表id
	ConfId           *int32 `protobuf:"varint,2,opt,name=confId" json:"confId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerConfirmBroadcastC2S) Reset()                    { *m = GamerConfirmBroadcastC2S{} }
func (m *GamerConfirmBroadcastC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerConfirmBroadcastC2S) ProtoMessage()               {}
func (*GamerConfirmBroadcastC2S) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{13} }

func (m *GamerConfirmBroadcastC2S) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GamerConfirmBroadcastC2S) GetConfId() int32 {
	if m != nil && m.ConfId != nil {
		return *m.ConfId
	}
	return 0
}

// 请求系统跑马灯
type SystemBroadcastC2S struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SystemBroadcastC2S) Reset()                    { *m = SystemBroadcastC2S{} }
func (m *SystemBroadcastC2S) String() string            { return proto.CompactTextString(m) }
func (*SystemBroadcastC2S) ProtoMessage()               {}
func (*SystemBroadcastC2S) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{14} }

// 返回 系统跑马灯列表
// @Gamer
type SystemBroadcastS2C struct {
	// 跑马灯列表
	BroadcastList    []*SystemBroadcast `protobuf:"bytes,1,rep,name=broadcastList" json:"broadcastList,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SystemBroadcastS2C) Reset()                    { *m = SystemBroadcastS2C{} }
func (m *SystemBroadcastS2C) String() string            { return proto.CompactTextString(m) }
func (*SystemBroadcastS2C) ProtoMessage()               {}
func (*SystemBroadcastS2C) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{15} }

func (m *SystemBroadcastS2C) GetBroadcastList() []*SystemBroadcast {
	if m != nil {
		return m.BroadcastList
	}
	return nil
}

func init() {
	proto.RegisterType((*GamerSendChatInfoC2S)(nil), "GamerSendChatInfoC2S")
	proto.RegisterType((*GamerSendChatInfoS2C)(nil), "GamerSendChatInfoS2C")
	proto.RegisterType((*GamerReceiveChatInfoS2C)(nil), "GamerReceiveChatInfoS2C")
	proto.RegisterType((*GamerGetPrivateChatC2S)(nil), "GamerGetPrivateChatC2S")
	proto.RegisterType((*GamerGetPrivateChatS2C)(nil), "GamerGetPrivateChatS2C")
	proto.RegisterType((*GamerDelPrivateChatC2S)(nil), "GamerDelPrivateChatC2S")
	proto.RegisterType((*GamerDelPrivateChatS2C)(nil), "GamerDelPrivateChatS2C")
	proto.RegisterType((*GamerReadChatC2S)(nil), "GamerReadChatC2S")
	proto.RegisterType((*GamerReadChatS2C)(nil), "GamerReadChatS2C")
	proto.RegisterType((*SendChatInfoToMatchL2M)(nil), "SendChatInfoToMatchL2M")
	proto.RegisterType((*GamerBroadcastRarePlayerS2C)(nil), "GamerBroadcastRarePlayerS2C")
	proto.RegisterType((*NotifyGamerBroadcastRarePlayer)(nil), "NotifyGamerBroadcastRarePlayer")
	proto.RegisterType((*SystemBroadcast)(nil), "SystemBroadcast")
	proto.RegisterType((*GamerConfirmBroadcastC2S)(nil), "GamerConfirmBroadcastC2S")
	proto.RegisterType((*SystemBroadcastC2S)(nil), "SystemBroadcastC2S")
	proto.RegisterType((*SystemBroadcastS2C)(nil), "SystemBroadcastS2C")
	proto.RegisterEnum("GamerSendChatInfoC2S_MsgID", GamerSendChatInfoC2S_MsgID_name, GamerSendChatInfoC2S_MsgID_value)
	proto.RegisterEnum("GamerSendChatInfoS2C_MsgID", GamerSendChatInfoS2C_MsgID_name, GamerSendChatInfoS2C_MsgID_value)
	proto.RegisterEnum("GamerReceiveChatInfoS2C_MsgID", GamerReceiveChatInfoS2C_MsgID_name, GamerReceiveChatInfoS2C_MsgID_value)
	proto.RegisterEnum("GamerGetPrivateChatC2S_MsgID", GamerGetPrivateChatC2S_MsgID_name, GamerGetPrivateChatC2S_MsgID_value)
	proto.RegisterEnum("GamerGetPrivateChatS2C_MsgID", GamerGetPrivateChatS2C_MsgID_name, GamerGetPrivateChatS2C_MsgID_value)
	proto.RegisterEnum("GamerDelPrivateChatC2S_MsgID", GamerDelPrivateChatC2S_MsgID_name, GamerDelPrivateChatC2S_MsgID_value)
	proto.RegisterEnum("GamerDelPrivateChatS2C_MsgID", GamerDelPrivateChatS2C_MsgID_name, GamerDelPrivateChatS2C_MsgID_value)
	proto.RegisterEnum("GamerReadChatC2S_MsgID", GamerReadChatC2S_MsgID_name, GamerReadChatC2S_MsgID_value)
	proto.RegisterEnum("GamerReadChatS2C_MsgID", GamerReadChatS2C_MsgID_name, GamerReadChatS2C_MsgID_value)
	proto.RegisterEnum("GamerBroadcastRarePlayerS2C_MsgID", GamerBroadcastRarePlayerS2C_MsgID_name, GamerBroadcastRarePlayerS2C_MsgID_value)
	proto.RegisterEnum("GamerConfirmBroadcastC2S_MsgID", GamerConfirmBroadcastC2S_MsgID_name, GamerConfirmBroadcastC2S_MsgID_value)
	proto.RegisterEnum("SystemBroadcastC2S_MsgID", SystemBroadcastC2S_MsgID_name, SystemBroadcastC2S_MsgID_value)
	proto.RegisterEnum("SystemBroadcastS2C_MsgID", SystemBroadcastS2C_MsgID_name, SystemBroadcastS2C_MsgID_value)
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xdf, 0x6b, 0x13, 0x41,
	0x10, 0xe6, 0x9a, 0xe6, 0xd7, 0x64, 0xdb, 0xc4, 0xb3, 0xd4, 0xb3, 0x82, 0xc8, 0x81, 0x28, 0x3e,
	0xe4, 0x21, 0x6f, 0xe2, 0x83, 0x60, 0x0a, 0x25, 0x92, 0x48, 0x49, 0xf2, 0x2e, 0xdb, 0xcd, 0x26,
	0x5d, 0xbc, 0xdb, 0x8d, 0x7b, 0x4b, 0x30, 0xfe, 0x03, 0xe2, 0x8b, 0xbf, 0x11, 0xc4, 0x7f, 0xd6,
	0xd9, 0xbd, 0x4b, 0x93, 0xa6, 0x77, 0x5a, 0xe9, 0xdb, 0xcd, 0xec, 0xcc, 0xf7, 0x7d, 0xfb, 0xed,
	0xcc, 0x01, 0xb0, 0x73, 0x6a, 0xda, 0x73, 0xad, 0x8c, 0x3a, 0x6a, 0xc4, 0x94, 0x69, 0x95, 0x05,
	0x84, 0xa9, 0x38, 0x56, 0x32, 0x8d, 0xc2, 0x0f, 0x1e, 0x1c, 0x9c, 0xd0, 0x98, 0xeb, 0x11, 0x97,
	0x93, 0x2e, 0xb6, 0xf4, 0xe4, 0x54, 0x75, 0x3b, 0x23, 0xff, 0x21, 0x34, 0x2d, 0x02, 0xa6, 0xa4,
	0xe4, 0xd1, 0x78, 0x39, 0xe7, 0x81, 0xf7, 0xc0, 0x7b, 0xbc, 0xdf, 0x21, 0xed, 0xee, 0x3a, 0xef,
	0xb7, 0xa0, 0x66, 0xcb, 0xdc, 0xf9, 0x0e, 0x9e, 0x97, 0x57, 0x19, 0x8b, 0x13, 0x94, 0x30, 0x43,
	0xfc, 0x7d, 0xa8, 0x68, 0xce, 0x16, 0xbd, 0x49, 0xb0, 0x6b, 0x2b, 0xc2, 0x03, 0x28, 0x0f, 0x92,
	0x59, 0xef, 0xd8, 0x6f, 0x40, 0x85, 0xbb, 0xaf, 0xd6, 0x27, 0x12, 0xfe, 0xca, 0x53, 0x32, 0xea,
	0x74, 0x2f, 0x51, 0x78, 0x57, 0x28, 0x76, 0x1c, 0x05, 0x66, 0x12, 0x6c, 0x1b, 0x8b, 0x98, 0x3b,
	0xd2, 0x52, 0x9e, 0xfe, 0xdd, 0x1c, 0xfd, 0x6b, 0x6d, 0xe5, 0xbf, 0x68, 0x7b, 0x0b, 0x77, 0x9c,
	0xb4, 0x21, 0x67, 0x5c, 0x2c, 0xf8, 0xa6, 0xba, 0x6b, 0xfa, 0x74, 0x17, 0xaa, 0xb6, 0xac, 0xaf,
	0x66, 0x4e, 0x71, 0xa3, 0x53, 0x73, 0xc7, 0x18, 0xe7, 0x51, 0x7e, 0x26, 0x61, 0x1b, 0x0e, 0x1d,
	0xe5, 0x09, 0x37, 0xa7, 0x5a, 0x2c, 0xa8, 0x71, 0xac, 0xf8, 0x32, 0x79, 0xf5, 0x5f, 0x48, 0xf8,
	0x32, 0xb7, 0xde, 0x2a, 0x3c, 0x4a, 0xdd, 0x42, 0xaa, 0x04, 0xa5, 0x95, 0xfe, 0xc5, 0x8d, 0x58,
	0xcf, 0x33, 0xac, 0x63, 0x1e, 0x5d, 0xe6, 0xf6, 0x9b, 0x50, 0x9d, 0xd9, 0x13, 0xf4, 0xcb, 0x2b,
	0xf2, 0xeb, 0x6b, 0x11, 0x80, 0x15, 0x73, 0x4d, 0x80, 0xa7, 0xd0, 0xca, 0x0c, 0xa7, 0x93, 0xff,
	0xe1, 0xfe, 0x46, 0xc2, 0x67, 0x5b, 0xad, 0x96, 0xf5, 0x16, 0xd4, 0x71, 0xdc, 0x19, 0x4f, 0x12,
	0x9e, 0x36, 0xd7, 0x0a, 0x9a, 0x7f, 0x7b, 0x70, 0xb8, 0x39, 0x7f, 0x63, 0x35, 0xa0, 0x86, 0x9d,
	0xf7, 0x3b, 0x83, 0x9b, 0x3f, 0xb4, 0x9d, 0xb5, 0xf7, 0x4a, 0xf2, 0xd5, 0x1e, 0xf8, 0xb7, 0xa1,
	0x61, 0x87, 0x16, 0x8f, 0x04, 0x5b, 0x0d, 0x20, 0xbe, 0x96, 0x4f, 0xa3, 0x48, 0x50, 0xc9, 0xf8,
	0x69, 0x44, 0x97, 0x5c, 0xf7, 0x45, 0x62, 0x82, 0x0a, 0xbe, 0x5b, 0x39, 0x9c, 0xc3, 0x3d, 0x77,
	0xb5, 0x17, 0x5a, 0xd1, 0x09, 0xa3, 0x89, 0x19, 0x52, 0x9d, 0x55, 0xd9, 0x5b, 0x12, 0xd8, 0x35,
	0xeb, 0x25, 0x41, 0xbb, 0xe6, 0x54, 0xd3, 0x18, 0x91, 0xd3, 0xc5, 0x44, 0x7a, 0xa6, 0xe4, 0x14,
	0xe3, 0x92, 0x8b, 0xb1, 0x5c, 0x22, 0x9a, 0x13, 0x53, 0xcf, 0xf3, 0xe3, 0x3b, 0x09, 0xdf, 0xc0,
	0xfd, 0x57, 0xca, 0x88, 0xe9, 0xb2, 0x88, 0xf7, 0x46, 0xa4, 0x36, 0x8a, 0x92, 0x8b, 0xdd, 0xfb,
	0xe8, 0x41, 0x73, 0xb4, 0x4c, 0x0c, 0x8f, 0x2f, 0x88, 0xfc, 0x3d, 0x28, 0x0b, 0x39, 0xe1, 0xef,
	0x32, 0x7c, 0x0c, 0x0d, 0xee, 0x78, 0x92, 0xa1, 0x37, 0x9d, 0xd9, 0xd6, 0x77, 0x07, 0x5f, 0xb7,
	0xff, 0x01, 0x21, 0x0d, 0xd7, 0x0b, 0x1a, 0x65, 0x26, 0xfb, 0x00, 0x67, 0x7c, 0x26, 0xe4, 0x6b,
	0xdb, 0xe7, 0x88, 0x4a, 0xb6, 0x0a, 0x7d, 0x4f, 0x33, 0x15, 0x97, 0xb1, 0x40, 0x0a, 0x1b, 0xa5,
	0x09, 0xaa, 0xce, 0x8e, 0x21, 0x04, 0xee, 0xca, 0x5d, 0x14, 0x2f, 0xf4, 0x5a, 0x90, 0x1d, 0x44,
	0x6c, 0x9f, 0xbb, 0xcb, 0xaf, 0x26, 0x71, 0xe3, 0x96, 0x3b, 0x45, 0x93, 0xf9, 0x83, 0x84, 0x4f,
	0xc0, 0xdf, 0xba, 0x5e, 0xc1, 0x3a, 0xff, 0x24, 0xe1, 0xe8, 0x4a, 0xad, 0x7d, 0xe1, 0x47, 0xb0,
	0x77, 0xb6, 0x8a, 0xdd, 0x5c, 0xa4, 0xfb, 0xdc, 0x6a, 0x6f, 0xd5, 0xe6, 0x83, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xfc, 0xa0, 0x7d, 0x0d, 0x14, 0x06, 0x00, 0x00,
}
