// Code generated by protoc-gen-go.
// source: condition.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SendConditionDataS2C_MsgID int32

const (
	SendConditionDataS2C_eMsgID SendConditionDataS2C_MsgID = 8705
)

var SendConditionDataS2C_MsgID_name = map[int32]string{
	8705: "eMsgID",
}
var SendConditionDataS2C_MsgID_value = map[string]int32{
	"eMsgID": 8705,
}

func (x SendConditionDataS2C_MsgID) Enum() *SendConditionDataS2C_MsgID {
	p := new(SendConditionDataS2C_MsgID)
	*p = x
	return p
}
func (x SendConditionDataS2C_MsgID) String() string {
	return proto.EnumName(SendConditionDataS2C_MsgID_name, int32(x))
}
func (x *SendConditionDataS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SendConditionDataS2C_MsgID_value, data, "SendConditionDataS2C_MsgID")
	if err != nil {
		return err
	}
	*x = SendConditionDataS2C_MsgID(value)
	return nil
}
func (SendConditionDataS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor17, []int{1, 0}
}

type DeleteConditionsS2C_MsgID int32

const (
	DeleteConditionsS2C_eMsgID DeleteConditionsS2C_MsgID = 8706
)

var DeleteConditionsS2C_MsgID_name = map[int32]string{
	8706: "eMsgID",
}
var DeleteConditionsS2C_MsgID_value = map[string]int32{
	"eMsgID": 8706,
}

func (x DeleteConditionsS2C_MsgID) Enum() *DeleteConditionsS2C_MsgID {
	p := new(DeleteConditionsS2C_MsgID)
	*p = x
	return p
}
func (x DeleteConditionsS2C_MsgID) String() string {
	return proto.EnumName(DeleteConditionsS2C_MsgID_name, int32(x))
}
func (x *DeleteConditionsS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DeleteConditionsS2C_MsgID_value, data, "DeleteConditionsS2C_MsgID")
	if err != nil {
		return err
	}
	*x = DeleteConditionsS2C_MsgID(value)
	return nil
}
func (DeleteConditionsS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor17, []int{2, 0}
}

// 条件数据
type ConditionData struct {
	// 配置id
	Id *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// 状态
	State *ConditionState `protobuf:"varint,2,opt,name=state,enum=ConditionState" json:"state,omitempty"`
	// 进度
	Progress         *int32 `protobuf:"varint,3,opt,name=progress" json:"progress,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConditionData) Reset()                    { *m = ConditionData{} }
func (m *ConditionData) String() string            { return proto.CompactTextString(m) }
func (*ConditionData) ProtoMessage()               {}
func (*ConditionData) Descriptor() ([]byte, []int) { return fileDescriptor17, []int{0} }

func (m *ConditionData) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ConditionData) GetState() ConditionState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ConditionState_CS_Processing
}

func (m *ConditionData) GetProgress() int32 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

// 发送条件数据
type SendConditionDataS2C struct {
	DataList         []*ConditionData `protobuf:"bytes,1,rep,name=dataList" json:"dataList,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SendConditionDataS2C) Reset()                    { *m = SendConditionDataS2C{} }
func (m *SendConditionDataS2C) String() string            { return proto.CompactTextString(m) }
func (*SendConditionDataS2C) ProtoMessage()               {}
func (*SendConditionDataS2C) Descriptor() ([]byte, []int) { return fileDescriptor17, []int{1} }

func (m *SendConditionDataS2C) GetDataList() []*ConditionData {
	if m != nil {
		return m.DataList
	}
	return nil
}

// 删除条件数据
type DeleteConditionsS2C struct {
	DataList         []int32 `protobuf:"varint,1,rep,name=dataList" json:"dataList,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteConditionsS2C) Reset()                    { *m = DeleteConditionsS2C{} }
func (m *DeleteConditionsS2C) String() string            { return proto.CompactTextString(m) }
func (*DeleteConditionsS2C) ProtoMessage()               {}
func (*DeleteConditionsS2C) Descriptor() ([]byte, []int) { return fileDescriptor17, []int{2} }

func (m *DeleteConditionsS2C) GetDataList() []int32 {
	if m != nil {
		return m.DataList
	}
	return nil
}

func init() {
	proto.RegisterType((*ConditionData)(nil), "ConditionData")
	proto.RegisterType((*SendConditionDataS2C)(nil), "SendConditionDataS2C")
	proto.RegisterType((*DeleteConditionsS2C)(nil), "DeleteConditionsS2C")
	proto.RegisterEnum("SendConditionDataS2C_MsgID", SendConditionDataS2C_MsgID_name, SendConditionDataS2C_MsgID_value)
	proto.RegisterEnum("DeleteConditionsS2C_MsgID", DeleteConditionsS2C_MsgID_name, DeleteConditionsS2C_MsgID_value)
}

func init() { proto.RegisterFile("condition.proto", fileDescriptor17) }

var fileDescriptor17 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xcf, 0x4b,
	0xc9, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0xce, 0x4d, 0x4c,
	0x2e, 0xca, 0x87, 0x70, 0x94, 0x7c, 0xb9, 0x78, 0x9d, 0x61, 0xf2, 0x2e, 0x89, 0x25, 0x89, 0x42,
	0x5c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x42, 0x72, 0x5c, 0xac, 0xc5,
	0x25, 0x89, 0x25, 0xa9, 0x12, 0x4c, 0x40, 0x2e, 0x9f, 0x11, 0xbf, 0x1e, 0x5c, 0x69, 0x30, 0x48,
	0x58, 0x48, 0x80, 0x8b, 0x03, 0x68, 0x4a, 0x7a, 0x51, 0x6a, 0x71, 0xb1, 0x04, 0x33, 0x48, 0x87,
	0x92, 0x1f, 0x97, 0x48, 0x70, 0x6a, 0x5e, 0x0a, 0x8a, 0x91, 0xc1, 0x46, 0xce, 0x42, 0x0a, 0x5c,
	0x1c, 0x29, 0x40, 0xa6, 0x4f, 0x66, 0x71, 0x09, 0xd0, 0x6c, 0x66, 0x0d, 0x6e, 0x23, 0x3e, 0x3d,
	0x14, 0x45, 0x4a, 0x22, 0x5c, 0xac, 0xbe, 0xc5, 0xe9, 0x9e, 0x2e, 0x42, 0xdc, 0x5c, 0x6c, 0xa9,
	0x60, 0x96, 0x40, 0xa3, 0x8b, 0x92, 0x2d, 0x97, 0xb0, 0x4b, 0x6a, 0x4e, 0x6a, 0x49, 0x2a, 0x5c,
	0x71, 0x31, 0xc8, 0x38, 0x01, 0x34, 0xe3, 0x58, 0xb1, 0x69, 0x6f, 0x72, 0x01, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0xb5, 0x83, 0xa7, 0xfc, 0x00, 0x00, 0x00,
}
