// Code generated by protoc-gen-go.
// source: friend.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GamerFriendGetInfoC2S_MsgID int32

const (
	GamerFriendGetInfoC2S_eMsgID GamerFriendGetInfoC2S_MsgID = 1537
)

var GamerFriendGetInfoC2S_MsgID_name = map[int32]string{
	1537: "eMsgID",
}
var GamerFriendGetInfoC2S_MsgID_value = map[string]int32{
	"eMsgID": 1537,
}

func (x GamerFriendGetInfoC2S_MsgID) Enum() *GamerFriendGetInfoC2S_MsgID {
	p := new(GamerFriendGetInfoC2S_MsgID)
	*p = x
	return p
}
func (x GamerFriendGetInfoC2S_MsgID) String() string {
	return proto.EnumName(GamerFriendGetInfoC2S_MsgID_name, int32(x))
}
func (x *GamerFriendGetInfoC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerFriendGetInfoC2S_MsgID_value, data, "GamerFriendGetInfoC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerFriendGetInfoC2S_MsgID(value)
	return nil
}
func (GamerFriendGetInfoC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{0, 0}
}

type GamerFriendGetInfoS2C_MsgID int32

const (
	GamerFriendGetInfoS2C_eMsgID GamerFriendGetInfoS2C_MsgID = 1537
)

var GamerFriendGetInfoS2C_MsgID_name = map[int32]string{
	1537: "eMsgID",
}
var GamerFriendGetInfoS2C_MsgID_value = map[string]int32{
	"eMsgID": 1537,
}

func (x GamerFriendGetInfoS2C_MsgID) Enum() *GamerFriendGetInfoS2C_MsgID {
	p := new(GamerFriendGetInfoS2C_MsgID)
	*p = x
	return p
}
func (x GamerFriendGetInfoS2C_MsgID) String() string {
	return proto.EnumName(GamerFriendGetInfoS2C_MsgID_name, int32(x))
}
func (x *GamerFriendGetInfoS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerFriendGetInfoS2C_MsgID_value, data, "GamerFriendGetInfoS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerFriendGetInfoS2C_MsgID(value)
	return nil
}
func (GamerFriendGetInfoS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{1, 0}
}

type GamerFindFriendC2S_MsgID int32

const (
	GamerFindFriendC2S_eMsgID GamerFindFriendC2S_MsgID = 1538
)

var GamerFindFriendC2S_MsgID_name = map[int32]string{
	1538: "eMsgID",
}
var GamerFindFriendC2S_MsgID_value = map[string]int32{
	"eMsgID": 1538,
}

func (x GamerFindFriendC2S_MsgID) Enum() *GamerFindFriendC2S_MsgID {
	p := new(GamerFindFriendC2S_MsgID)
	*p = x
	return p
}
func (x GamerFindFriendC2S_MsgID) String() string {
	return proto.EnumName(GamerFindFriendC2S_MsgID_name, int32(x))
}
func (x *GamerFindFriendC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerFindFriendC2S_MsgID_value, data, "GamerFindFriendC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerFindFriendC2S_MsgID(value)
	return nil
}
func (GamerFindFriendC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{2, 0}
}

type GamerFindFriendS2C_MsgID int32

const (
	GamerFindFriendS2C_eMsgID GamerFindFriendS2C_MsgID = 1538
)

var GamerFindFriendS2C_MsgID_name = map[int32]string{
	1538: "eMsgID",
}
var GamerFindFriendS2C_MsgID_value = map[string]int32{
	"eMsgID": 1538,
}

func (x GamerFindFriendS2C_MsgID) Enum() *GamerFindFriendS2C_MsgID {
	p := new(GamerFindFriendS2C_MsgID)
	*p = x
	return p
}
func (x GamerFindFriendS2C_MsgID) String() string {
	return proto.EnumName(GamerFindFriendS2C_MsgID_name, int32(x))
}
func (x *GamerFindFriendS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerFindFriendS2C_MsgID_value, data, "GamerFindFriendS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerFindFriendS2C_MsgID(value)
	return nil
}
func (GamerFindFriendS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{3, 0}
}

type GamerAddFriendC2S_MsgID int32

const (
	GamerAddFriendC2S_eMsgID GamerAddFriendC2S_MsgID = 1539
)

var GamerAddFriendC2S_MsgID_name = map[int32]string{
	1539: "eMsgID",
}
var GamerAddFriendC2S_MsgID_value = map[string]int32{
	"eMsgID": 1539,
}

func (x GamerAddFriendC2S_MsgID) Enum() *GamerAddFriendC2S_MsgID {
	p := new(GamerAddFriendC2S_MsgID)
	*p = x
	return p
}
func (x GamerAddFriendC2S_MsgID) String() string {
	return proto.EnumName(GamerAddFriendC2S_MsgID_name, int32(x))
}
func (x *GamerAddFriendC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerAddFriendC2S_MsgID_value, data, "GamerAddFriendC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerAddFriendC2S_MsgID(value)
	return nil
}
func (GamerAddFriendC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{4, 0} }

type GamerAddFriendS2C_MsgID int32

const (
	GamerAddFriendS2C_eMsgID GamerAddFriendS2C_MsgID = 1539
)

var GamerAddFriendS2C_MsgID_name = map[int32]string{
	1539: "eMsgID",
}
var GamerAddFriendS2C_MsgID_value = map[string]int32{
	"eMsgID": 1539,
}

func (x GamerAddFriendS2C_MsgID) Enum() *GamerAddFriendS2C_MsgID {
	p := new(GamerAddFriendS2C_MsgID)
	*p = x
	return p
}
func (x GamerAddFriendS2C_MsgID) String() string {
	return proto.EnumName(GamerAddFriendS2C_MsgID_name, int32(x))
}
func (x *GamerAddFriendS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerAddFriendS2C_MsgID_value, data, "GamerAddFriendS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerAddFriendS2C_MsgID(value)
	return nil
}
func (GamerAddFriendS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{5, 0} }

type NotifyAddFriendRequestS2C_MsgID int32

const (
	NotifyAddFriendRequestS2C_eMsgID NotifyAddFriendRequestS2C_MsgID = 64822
)

var NotifyAddFriendRequestS2C_MsgID_name = map[int32]string{
	64822: "eMsgID",
}
var NotifyAddFriendRequestS2C_MsgID_value = map[string]int32{
	"eMsgID": 64822,
}

func (x NotifyAddFriendRequestS2C_MsgID) Enum() *NotifyAddFriendRequestS2C_MsgID {
	p := new(NotifyAddFriendRequestS2C_MsgID)
	*p = x
	return p
}
func (x NotifyAddFriendRequestS2C_MsgID) String() string {
	return proto.EnumName(NotifyAddFriendRequestS2C_MsgID_name, int32(x))
}
func (x *NotifyAddFriendRequestS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NotifyAddFriendRequestS2C_MsgID_value, data, "NotifyAddFriendRequestS2C_MsgID")
	if err != nil {
		return err
	}
	*x = NotifyAddFriendRequestS2C_MsgID(value)
	return nil
}
func (NotifyAddFriendRequestS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{6, 0}
}

type GamerDelFriendC2S_MsgID int32

const (
	GamerDelFriendC2S_eMsgID GamerDelFriendC2S_MsgID = 1540
)

var GamerDelFriendC2S_MsgID_name = map[int32]string{
	1540: "eMsgID",
}
var GamerDelFriendC2S_MsgID_value = map[string]int32{
	"eMsgID": 1540,
}

func (x GamerDelFriendC2S_MsgID) Enum() *GamerDelFriendC2S_MsgID {
	p := new(GamerDelFriendC2S_MsgID)
	*p = x
	return p
}
func (x GamerDelFriendC2S_MsgID) String() string {
	return proto.EnumName(GamerDelFriendC2S_MsgID_name, int32(x))
}
func (x *GamerDelFriendC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDelFriendC2S_MsgID_value, data, "GamerDelFriendC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDelFriendC2S_MsgID(value)
	return nil
}
func (GamerDelFriendC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{7, 0} }

type GamerDelFriendS2C_MsgID int32

const (
	GamerDelFriendS2C_eMsgID GamerDelFriendS2C_MsgID = 1540
)

var GamerDelFriendS2C_MsgID_name = map[int32]string{
	1540: "eMsgID",
}
var GamerDelFriendS2C_MsgID_value = map[string]int32{
	"eMsgID": 1540,
}

func (x GamerDelFriendS2C_MsgID) Enum() *GamerDelFriendS2C_MsgID {
	p := new(GamerDelFriendS2C_MsgID)
	*p = x
	return p
}
func (x GamerDelFriendS2C_MsgID) String() string {
	return proto.EnumName(GamerDelFriendS2C_MsgID_name, int32(x))
}
func (x *GamerDelFriendS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDelFriendS2C_MsgID_value, data, "GamerDelFriendS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDelFriendS2C_MsgID(value)
	return nil
}
func (GamerDelFriendS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor27, []int{8, 0} }

type NotifyDelFriendS2C_MsgID int32

const (
	NotifyDelFriendS2C_eMsgID NotifyDelFriendS2C_MsgID = 64824
)

var NotifyDelFriendS2C_MsgID_name = map[int32]string{
	64824: "eMsgID",
}
var NotifyDelFriendS2C_MsgID_value = map[string]int32{
	"eMsgID": 64824,
}

func (x NotifyDelFriendS2C_MsgID) Enum() *NotifyDelFriendS2C_MsgID {
	p := new(NotifyDelFriendS2C_MsgID)
	*p = x
	return p
}
func (x NotifyDelFriendS2C_MsgID) String() string {
	return proto.EnumName(NotifyDelFriendS2C_MsgID_name, int32(x))
}
func (x *NotifyDelFriendS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NotifyDelFriendS2C_MsgID_value, data, "NotifyDelFriendS2C_MsgID")
	if err != nil {
		return err
	}
	*x = NotifyDelFriendS2C_MsgID(value)
	return nil
}
func (NotifyDelFriendS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{9, 0}
}

type GamerSendFriendEnergyC2S_MsgID int32

const (
	GamerSendFriendEnergyC2S_eMsgID GamerSendFriendEnergyC2S_MsgID = 1541
)

var GamerSendFriendEnergyC2S_MsgID_name = map[int32]string{
	1541: "eMsgID",
}
var GamerSendFriendEnergyC2S_MsgID_value = map[string]int32{
	"eMsgID": 1541,
}

func (x GamerSendFriendEnergyC2S_MsgID) Enum() *GamerSendFriendEnergyC2S_MsgID {
	p := new(GamerSendFriendEnergyC2S_MsgID)
	*p = x
	return p
}
func (x GamerSendFriendEnergyC2S_MsgID) String() string {
	return proto.EnumName(GamerSendFriendEnergyC2S_MsgID_name, int32(x))
}
func (x *GamerSendFriendEnergyC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerSendFriendEnergyC2S_MsgID_value, data, "GamerSendFriendEnergyC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerSendFriendEnergyC2S_MsgID(value)
	return nil
}
func (GamerSendFriendEnergyC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{10, 0}
}

type GamerSendFriendEnergyS2C_MsgID int32

const (
	GamerSendFriendEnergyS2C_eMsgID GamerSendFriendEnergyS2C_MsgID = 1541
)

var GamerSendFriendEnergyS2C_MsgID_name = map[int32]string{
	1541: "eMsgID",
}
var GamerSendFriendEnergyS2C_MsgID_value = map[string]int32{
	"eMsgID": 1541,
}

func (x GamerSendFriendEnergyS2C_MsgID) Enum() *GamerSendFriendEnergyS2C_MsgID {
	p := new(GamerSendFriendEnergyS2C_MsgID)
	*p = x
	return p
}
func (x GamerSendFriendEnergyS2C_MsgID) String() string {
	return proto.EnumName(GamerSendFriendEnergyS2C_MsgID_name, int32(x))
}
func (x *GamerSendFriendEnergyS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerSendFriendEnergyS2C_MsgID_value, data, "GamerSendFriendEnergyS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerSendFriendEnergyS2C_MsgID(value)
	return nil
}
func (GamerSendFriendEnergyS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{11, 0}
}

type NotifySendFriendEnergyS2C_MsgID int32

const (
	NotifySendFriendEnergyS2C_eMsgID NotifySendFriendEnergyS2C_MsgID = 64825
)

var NotifySendFriendEnergyS2C_MsgID_name = map[int32]string{
	64825: "eMsgID",
}
var NotifySendFriendEnergyS2C_MsgID_value = map[string]int32{
	"eMsgID": 64825,
}

func (x NotifySendFriendEnergyS2C_MsgID) Enum() *NotifySendFriendEnergyS2C_MsgID {
	p := new(NotifySendFriendEnergyS2C_MsgID)
	*p = x
	return p
}
func (x NotifySendFriendEnergyS2C_MsgID) String() string {
	return proto.EnumName(NotifySendFriendEnergyS2C_MsgID_name, int32(x))
}
func (x *NotifySendFriendEnergyS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NotifySendFriendEnergyS2C_MsgID_value, data, "NotifySendFriendEnergyS2C_MsgID")
	if err != nil {
		return err
	}
	*x = NotifySendFriendEnergyS2C_MsgID(value)
	return nil
}
func (NotifySendFriendEnergyS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{12, 0}
}

type GamerDrawFriendEnergyC2S_MsgID int32

const (
	GamerDrawFriendEnergyC2S_eMsgID GamerDrawFriendEnergyC2S_MsgID = 1542
)

var GamerDrawFriendEnergyC2S_MsgID_name = map[int32]string{
	1542: "eMsgID",
}
var GamerDrawFriendEnergyC2S_MsgID_value = map[string]int32{
	"eMsgID": 1542,
}

func (x GamerDrawFriendEnergyC2S_MsgID) Enum() *GamerDrawFriendEnergyC2S_MsgID {
	p := new(GamerDrawFriendEnergyC2S_MsgID)
	*p = x
	return p
}
func (x GamerDrawFriendEnergyC2S_MsgID) String() string {
	return proto.EnumName(GamerDrawFriendEnergyC2S_MsgID_name, int32(x))
}
func (x *GamerDrawFriendEnergyC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDrawFriendEnergyC2S_MsgID_value, data, "GamerDrawFriendEnergyC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDrawFriendEnergyC2S_MsgID(value)
	return nil
}
func (GamerDrawFriendEnergyC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{13, 0}
}

type GamerDrawFriendEnergyS2C_MsgID int32

const (
	GamerDrawFriendEnergyS2C_eMsgID GamerDrawFriendEnergyS2C_MsgID = 1542
)

var GamerDrawFriendEnergyS2C_MsgID_name = map[int32]string{
	1542: "eMsgID",
}
var GamerDrawFriendEnergyS2C_MsgID_value = map[string]int32{
	"eMsgID": 1542,
}

func (x GamerDrawFriendEnergyS2C_MsgID) Enum() *GamerDrawFriendEnergyS2C_MsgID {
	p := new(GamerDrawFriendEnergyS2C_MsgID)
	*p = x
	return p
}
func (x GamerDrawFriendEnergyS2C_MsgID) String() string {
	return proto.EnumName(GamerDrawFriendEnergyS2C_MsgID_name, int32(x))
}
func (x *GamerDrawFriendEnergyS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDrawFriendEnergyS2C_MsgID_value, data, "GamerDrawFriendEnergyS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDrawFriendEnergyS2C_MsgID(value)
	return nil
}
func (GamerDrawFriendEnergyS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{14, 0}
}

type GamerFriendRequestGetInfoC2S_MsgID int32

const (
	GamerFriendRequestGetInfoC2S_eMsgID GamerFriendRequestGetInfoC2S_MsgID = 1543
)

var GamerFriendRequestGetInfoC2S_MsgID_name = map[int32]string{
	1543: "eMsgID",
}
var GamerFriendRequestGetInfoC2S_MsgID_value = map[string]int32{
	"eMsgID": 1543,
}

func (x GamerFriendRequestGetInfoC2S_MsgID) Enum() *GamerFriendRequestGetInfoC2S_MsgID {
	p := new(GamerFriendRequestGetInfoC2S_MsgID)
	*p = x
	return p
}
func (x GamerFriendRequestGetInfoC2S_MsgID) String() string {
	return proto.EnumName(GamerFriendRequestGetInfoC2S_MsgID_name, int32(x))
}
func (x *GamerFriendRequestGetInfoC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerFriendRequestGetInfoC2S_MsgID_value, data, "GamerFriendRequestGetInfoC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerFriendRequestGetInfoC2S_MsgID(value)
	return nil
}
func (GamerFriendRequestGetInfoC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{15, 0}
}

type GamerFriendRequestGetInfoS2C_MsgID int32

const (
	GamerFriendRequestGetInfoS2C_eMsgID GamerFriendRequestGetInfoS2C_MsgID = 1543
)

var GamerFriendRequestGetInfoS2C_MsgID_name = map[int32]string{
	1543: "eMsgID",
}
var GamerFriendRequestGetInfoS2C_MsgID_value = map[string]int32{
	"eMsgID": 1543,
}

func (x GamerFriendRequestGetInfoS2C_MsgID) Enum() *GamerFriendRequestGetInfoS2C_MsgID {
	p := new(GamerFriendRequestGetInfoS2C_MsgID)
	*p = x
	return p
}
func (x GamerFriendRequestGetInfoS2C_MsgID) String() string {
	return proto.EnumName(GamerFriendRequestGetInfoS2C_MsgID_name, int32(x))
}
func (x *GamerFriendRequestGetInfoS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerFriendRequestGetInfoS2C_MsgID_value, data, "GamerFriendRequestGetInfoS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerFriendRequestGetInfoS2C_MsgID(value)
	return nil
}
func (GamerFriendRequestGetInfoS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{16, 0}
}

type GamerGetPlayerTeamInfoC2S_MsgID int32

const (
	GamerGetPlayerTeamInfoC2S_eMsgID GamerGetPlayerTeamInfoC2S_MsgID = 1544
)

var GamerGetPlayerTeamInfoC2S_MsgID_name = map[int32]string{
	1544: "eMsgID",
}
var GamerGetPlayerTeamInfoC2S_MsgID_value = map[string]int32{
	"eMsgID": 1544,
}

func (x GamerGetPlayerTeamInfoC2S_MsgID) Enum() *GamerGetPlayerTeamInfoC2S_MsgID {
	p := new(GamerGetPlayerTeamInfoC2S_MsgID)
	*p = x
	return p
}
func (x GamerGetPlayerTeamInfoC2S_MsgID) String() string {
	return proto.EnumName(GamerGetPlayerTeamInfoC2S_MsgID_name, int32(x))
}
func (x *GamerGetPlayerTeamInfoC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerGetPlayerTeamInfoC2S_MsgID_value, data, "GamerGetPlayerTeamInfoC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerGetPlayerTeamInfoC2S_MsgID(value)
	return nil
}
func (GamerGetPlayerTeamInfoC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{17, 0}
}

type GamerGetPlayerTeamInfoS2C_MsgID int32

const (
	GamerGetPlayerTeamInfoS2C_eMsgID GamerGetPlayerTeamInfoS2C_MsgID = 1544
)

var GamerGetPlayerTeamInfoS2C_MsgID_name = map[int32]string{
	1544: "eMsgID",
}
var GamerGetPlayerTeamInfoS2C_MsgID_value = map[string]int32{
	"eMsgID": 1544,
}

func (x GamerGetPlayerTeamInfoS2C_MsgID) Enum() *GamerGetPlayerTeamInfoS2C_MsgID {
	p := new(GamerGetPlayerTeamInfoS2C_MsgID)
	*p = x
	return p
}
func (x GamerGetPlayerTeamInfoS2C_MsgID) String() string {
	return proto.EnumName(GamerGetPlayerTeamInfoS2C_MsgID_name, int32(x))
}
func (x *GamerGetPlayerTeamInfoS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerGetPlayerTeamInfoS2C_MsgID_value, data, "GamerGetPlayerTeamInfoS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerGetPlayerTeamInfoS2C_MsgID(value)
	return nil
}
func (GamerGetPlayerTeamInfoS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{18, 0}
}

type GamerDealFriendRequestC2S_MsgID int32

const (
	GamerDealFriendRequestC2S_eMsgID GamerDealFriendRequestC2S_MsgID = 1545
)

var GamerDealFriendRequestC2S_MsgID_name = map[int32]string{
	1545: "eMsgID",
}
var GamerDealFriendRequestC2S_MsgID_value = map[string]int32{
	"eMsgID": 1545,
}

func (x GamerDealFriendRequestC2S_MsgID) Enum() *GamerDealFriendRequestC2S_MsgID {
	p := new(GamerDealFriendRequestC2S_MsgID)
	*p = x
	return p
}
func (x GamerDealFriendRequestC2S_MsgID) String() string {
	return proto.EnumName(GamerDealFriendRequestC2S_MsgID_name, int32(x))
}
func (x *GamerDealFriendRequestC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDealFriendRequestC2S_MsgID_value, data, "GamerDealFriendRequestC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDealFriendRequestC2S_MsgID(value)
	return nil
}
func (GamerDealFriendRequestC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{19, 0}
}

type GamerDealFriendRequestS2C_MsgID int32

const (
	GamerDealFriendRequestS2C_eMsgID GamerDealFriendRequestS2C_MsgID = 1545
)

var GamerDealFriendRequestS2C_MsgID_name = map[int32]string{
	1545: "eMsgID",
}
var GamerDealFriendRequestS2C_MsgID_value = map[string]int32{
	"eMsgID": 1545,
}

func (x GamerDealFriendRequestS2C_MsgID) Enum() *GamerDealFriendRequestS2C_MsgID {
	p := new(GamerDealFriendRequestS2C_MsgID)
	*p = x
	return p
}
func (x GamerDealFriendRequestS2C_MsgID) String() string {
	return proto.EnumName(GamerDealFriendRequestS2C_MsgID_name, int32(x))
}
func (x *GamerDealFriendRequestS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDealFriendRequestS2C_MsgID_value, data, "GamerDealFriendRequestS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDealFriendRequestS2C_MsgID(value)
	return nil
}
func (GamerDealFriendRequestS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{20, 0}
}

type NotifyDealFriendRequestS2C_MsgID int32

const (
	NotifyDealFriendRequestS2C_eMsgID NotifyDealFriendRequestS2C_MsgID = 64823
)

var NotifyDealFriendRequestS2C_MsgID_name = map[int32]string{
	64823: "eMsgID",
}
var NotifyDealFriendRequestS2C_MsgID_value = map[string]int32{
	"eMsgID": 64823,
}

func (x NotifyDealFriendRequestS2C_MsgID) Enum() *NotifyDealFriendRequestS2C_MsgID {
	p := new(NotifyDealFriendRequestS2C_MsgID)
	*p = x
	return p
}
func (x NotifyDealFriendRequestS2C_MsgID) String() string {
	return proto.EnumName(NotifyDealFriendRequestS2C_MsgID_name, int32(x))
}
func (x *NotifyDealFriendRequestS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NotifyDealFriendRequestS2C_MsgID_value, data, "NotifyDealFriendRequestS2C_MsgID")
	if err != nil {
		return err
	}
	*x = NotifyDealFriendRequestS2C_MsgID(value)
	return nil
}
func (NotifyDealFriendRequestS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{21, 0}
}

type GamerAddBackListC2S_MsgID int32

const (
	GamerAddBackListC2S_eMsgID GamerAddBackListC2S_MsgID = 1547
)

var GamerAddBackListC2S_MsgID_name = map[int32]string{
	1547: "eMsgID",
}
var GamerAddBackListC2S_MsgID_value = map[string]int32{
	"eMsgID": 1547,
}

func (x GamerAddBackListC2S_MsgID) Enum() *GamerAddBackListC2S_MsgID {
	p := new(GamerAddBackListC2S_MsgID)
	*p = x
	return p
}
func (x GamerAddBackListC2S_MsgID) String() string {
	return proto.EnumName(GamerAddBackListC2S_MsgID_name, int32(x))
}
func (x *GamerAddBackListC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerAddBackListC2S_MsgID_value, data, "GamerAddBackListC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerAddBackListC2S_MsgID(value)
	return nil
}
func (GamerAddBackListC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{22, 0}
}

type GamerAddBackListS2C_MsgID int32

const (
	GamerAddBackListS2C_eMsgID GamerAddBackListS2C_MsgID = 1547
)

var GamerAddBackListS2C_MsgID_name = map[int32]string{
	1547: "eMsgID",
}
var GamerAddBackListS2C_MsgID_value = map[string]int32{
	"eMsgID": 1547,
}

func (x GamerAddBackListS2C_MsgID) Enum() *GamerAddBackListS2C_MsgID {
	p := new(GamerAddBackListS2C_MsgID)
	*p = x
	return p
}
func (x GamerAddBackListS2C_MsgID) String() string {
	return proto.EnumName(GamerAddBackListS2C_MsgID_name, int32(x))
}
func (x *GamerAddBackListS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerAddBackListS2C_MsgID_value, data, "GamerAddBackListS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerAddBackListS2C_MsgID(value)
	return nil
}
func (GamerAddBackListS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{23, 0}
}

type GamerDelBackListC2S_MsgID int32

const (
	GamerDelBackListC2S_eMsgID GamerDelBackListC2S_MsgID = 1548
)

var GamerDelBackListC2S_MsgID_name = map[int32]string{
	1548: "eMsgID",
}
var GamerDelBackListC2S_MsgID_value = map[string]int32{
	"eMsgID": 1548,
}

func (x GamerDelBackListC2S_MsgID) Enum() *GamerDelBackListC2S_MsgID {
	p := new(GamerDelBackListC2S_MsgID)
	*p = x
	return p
}
func (x GamerDelBackListC2S_MsgID) String() string {
	return proto.EnumName(GamerDelBackListC2S_MsgID_name, int32(x))
}
func (x *GamerDelBackListC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDelBackListC2S_MsgID_value, data, "GamerDelBackListC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDelBackListC2S_MsgID(value)
	return nil
}
func (GamerDelBackListC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{24, 0}
}

type GamerDelBackListS2C_MsgID int32

const (
	GamerDelBackListS2C_eMsgID GamerDelBackListS2C_MsgID = 1548
)

var GamerDelBackListS2C_MsgID_name = map[int32]string{
	1548: "eMsgID",
}
var GamerDelBackListS2C_MsgID_value = map[string]int32{
	"eMsgID": 1548,
}

func (x GamerDelBackListS2C_MsgID) Enum() *GamerDelBackListS2C_MsgID {
	p := new(GamerDelBackListS2C_MsgID)
	*p = x
	return p
}
func (x GamerDelBackListS2C_MsgID) String() string {
	return proto.EnumName(GamerDelBackListS2C_MsgID_name, int32(x))
}
func (x *GamerDelBackListS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerDelBackListS2C_MsgID_value, data, "GamerDelBackListS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerDelBackListS2C_MsgID(value)
	return nil
}
func (GamerDelBackListS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{25, 0}
}

type GamerGetBackListInfoC2S_MsgID int32

const (
	GamerGetBackListInfoC2S_eMsgID GamerGetBackListInfoC2S_MsgID = 1549
)

var GamerGetBackListInfoC2S_MsgID_name = map[int32]string{
	1549: "eMsgID",
}
var GamerGetBackListInfoC2S_MsgID_value = map[string]int32{
	"eMsgID": 1549,
}

func (x GamerGetBackListInfoC2S_MsgID) Enum() *GamerGetBackListInfoC2S_MsgID {
	p := new(GamerGetBackListInfoC2S_MsgID)
	*p = x
	return p
}
func (x GamerGetBackListInfoC2S_MsgID) String() string {
	return proto.EnumName(GamerGetBackListInfoC2S_MsgID_name, int32(x))
}
func (x *GamerGetBackListInfoC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerGetBackListInfoC2S_MsgID_value, data, "GamerGetBackListInfoC2S_MsgID")
	if err != nil {
		return err
	}
	*x = GamerGetBackListInfoC2S_MsgID(value)
	return nil
}
func (GamerGetBackListInfoC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{26, 0}
}

type GamerGetBackListInfoS2C_MsgID int32

const (
	GamerGetBackListInfoS2C_eMsgID GamerGetBackListInfoS2C_MsgID = 1549
)

var GamerGetBackListInfoS2C_MsgID_name = map[int32]string{
	1549: "eMsgID",
}
var GamerGetBackListInfoS2C_MsgID_value = map[string]int32{
	"eMsgID": 1549,
}

func (x GamerGetBackListInfoS2C_MsgID) Enum() *GamerGetBackListInfoS2C_MsgID {
	p := new(GamerGetBackListInfoS2C_MsgID)
	*p = x
	return p
}
func (x GamerGetBackListInfoS2C_MsgID) String() string {
	return proto.EnumName(GamerGetBackListInfoS2C_MsgID_name, int32(x))
}
func (x *GamerGetBackListInfoS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerGetBackListInfoS2C_MsgID_value, data, "GamerGetBackListInfoS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerGetBackListInfoS2C_MsgID(value)
	return nil
}
func (GamerGetBackListInfoS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{27, 0}
}

type GamerInformFriendNameChangedS2C_MsgID int32

const (
	GamerInformFriendNameChangedS2C_eMsgID GamerInformFriendNameChangedS2C_MsgID = 1557
)

var GamerInformFriendNameChangedS2C_MsgID_name = map[int32]string{
	1557: "eMsgID",
}
var GamerInformFriendNameChangedS2C_MsgID_value = map[string]int32{
	"eMsgID": 1557,
}

func (x GamerInformFriendNameChangedS2C_MsgID) Enum() *GamerInformFriendNameChangedS2C_MsgID {
	p := new(GamerInformFriendNameChangedS2C_MsgID)
	*p = x
	return p
}
func (x GamerInformFriendNameChangedS2C_MsgID) String() string {
	return proto.EnumName(GamerInformFriendNameChangedS2C_MsgID_name, int32(x))
}
func (x *GamerInformFriendNameChangedS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GamerInformFriendNameChangedS2C_MsgID_value, data, "GamerInformFriendNameChangedS2C_MsgID")
	if err != nil {
		return err
	}
	*x = GamerInformFriendNameChangedS2C_MsgID(value)
	return nil
}
func (GamerInformFriendNameChangedS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor27, []int{28, 0}
}

// 获取好友信息
type GamerFriendGetInfoC2S struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerFriendGetInfoC2S) Reset()                    { *m = GamerFriendGetInfoC2S{} }
func (m *GamerFriendGetInfoC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerFriendGetInfoC2S) ProtoMessage()               {}
func (*GamerFriendGetInfoC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{0} }

// 获取好友信息
type GamerFriendGetInfoS2C struct {
	// 当日领取好友赠送体力次数
	EnergyRecvNum *int32 `protobuf:"varint,1,opt,name=energyRecvNum" json:"energyRecvNum,omitempty"`
	// 好友信息
	FrdDetails       []*FriendDetail `protobuf:"bytes,2,rep,name=frdDetails" json:"frdDetails,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GamerFriendGetInfoS2C) Reset()                    { *m = GamerFriendGetInfoS2C{} }
func (m *GamerFriendGetInfoS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerFriendGetInfoS2C) ProtoMessage()               {}
func (*GamerFriendGetInfoS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{1} }

func (m *GamerFriendGetInfoS2C) GetEnergyRecvNum() int32 {
	if m != nil && m.EnergyRecvNum != nil {
		return *m.EnergyRecvNum
	}
	return 0
}

func (m *GamerFriendGetInfoS2C) GetFrdDetails() []*FriendDetail {
	if m != nil {
		return m.FrdDetails
	}
	return nil
}

// 查找好友
type GamerFindFriendC2S struct {
	// 玩家名字或者id
	Key *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// 刷新推荐好友列表
	Recommend *bool `protobuf:"varint,2,opt,name=recommend" json:"recommend,omitempty"`
	// 刷新推荐列表时的开始位置
	Start            *int32 `protobuf:"varint,3,opt,name=start" json:"start,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerFindFriendC2S) Reset()                    { *m = GamerFindFriendC2S{} }
func (m *GamerFindFriendC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerFindFriendC2S) ProtoMessage()               {}
func (*GamerFindFriendC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{2} }

func (m *GamerFindFriendC2S) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GamerFindFriendC2S) GetRecommend() bool {
	if m != nil && m.Recommend != nil {
		return *m.Recommend
	}
	return false
}

func (m *GamerFindFriendC2S) GetStart() int32 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

// 查找好友
type GamerFindFriendS2C struct {
	// 好友信息
	FrdDetails []*FriendDetail `protobuf:"bytes,1,rep,name=frdDetails" json:"frdDetails,omitempty"`
	// 冷却时间
	RefershTime *int32 `protobuf:"varint,2,opt,name=refershTime" json:"refershTime,omitempty"`
	// 下次刷新推荐列表的开始位置
	NextStart *int32 `protobuf:"varint,3,opt,name=nextStart" json:"nextStart,omitempty"`
	// 刷新推荐好友列表
	Recommend        *bool  `protobuf:"varint,4,opt,name=recommend" json:"recommend,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerFindFriendS2C) Reset()                    { *m = GamerFindFriendS2C{} }
func (m *GamerFindFriendS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerFindFriendS2C) ProtoMessage()               {}
func (*GamerFindFriendS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{3} }

func (m *GamerFindFriendS2C) GetFrdDetails() []*FriendDetail {
	if m != nil {
		return m.FrdDetails
	}
	return nil
}

func (m *GamerFindFriendS2C) GetRefershTime() int32 {
	if m != nil && m.RefershTime != nil {
		return *m.RefershTime
	}
	return 0
}

func (m *GamerFindFriendS2C) GetNextStart() int32 {
	if m != nil && m.NextStart != nil {
		return *m.NextStart
	}
	return 0
}

func (m *GamerFindFriendS2C) GetRecommend() bool {
	if m != nil && m.Recommend != nil {
		return *m.Recommend
	}
	return false
}

// 申请加好友
type GamerAddFriendC2S struct {
	// 玩家ID列表
	FriendId         []int32 `protobuf:"varint,1,rep,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerAddFriendC2S) Reset()                    { *m = GamerAddFriendC2S{} }
func (m *GamerAddFriendC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerAddFriendC2S) ProtoMessage()               {}
func (*GamerAddFriendC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{4} }

func (m *GamerAddFriendC2S) GetFriendId() []int32 {
	if m != nil {
		return m.FriendId
	}
	return nil
}

// 申请加好友
type GamerAddFriendS2C struct {
	// 玩家ID列表
	FriendId         []int32 `protobuf:"varint,1,rep,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerAddFriendS2C) Reset()                    { *m = GamerAddFriendS2C{} }
func (m *GamerAddFriendS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerAddFriendS2C) ProtoMessage()               {}
func (*GamerAddFriendS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{5} }

func (m *GamerAddFriendS2C) GetFriendId() []int32 {
	if m != nil {
		return m.FriendId
	}
	return nil
}

// 通知客户端，有人申请加你为好友
type NotifyAddFriendRequestS2C struct {
	// 申请人简讯
	FrdReqDetail     *FriendRequestDetail `protobuf:"bytes,2,opt,name=frdReqDetail" json:"frdReqDetail,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *NotifyAddFriendRequestS2C) Reset()                    { *m = NotifyAddFriendRequestS2C{} }
func (m *NotifyAddFriendRequestS2C) String() string            { return proto.CompactTextString(m) }
func (*NotifyAddFriendRequestS2C) ProtoMessage()               {}
func (*NotifyAddFriendRequestS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{6} }

func (m *NotifyAddFriendRequestS2C) GetFrdReqDetail() *FriendRequestDetail {
	if m != nil {
		return m.FrdReqDetail
	}
	return nil
}

// 删除好友
type GamerDelFriendC2S struct {
	// 好友ID
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelFriendC2S) Reset()                    { *m = GamerDelFriendC2S{} }
func (m *GamerDelFriendC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerDelFriendC2S) ProtoMessage()               {}
func (*GamerDelFriendC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{7} }

func (m *GamerDelFriendC2S) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 删除好友
type GamerDelFriendS2C struct {
	// 好友ID
	FriendId         *int32 `protobuf:"varint,2,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelFriendS2C) Reset()                    { *m = GamerDelFriendS2C{} }
func (m *GamerDelFriendS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDelFriendS2C) ProtoMessage()               {}
func (*GamerDelFriendS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{8} }

func (m *GamerDelFriendS2C) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 通知玩家、删除好友
type NotifyDelFriendS2C struct {
	// 好友ID
	FriendId         *int32 `protobuf:"varint,2,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyDelFriendS2C) Reset()                    { *m = NotifyDelFriendS2C{} }
func (m *NotifyDelFriendS2C) String() string            { return proto.CompactTextString(m) }
func (*NotifyDelFriendS2C) ProtoMessage()               {}
func (*NotifyDelFriendS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{9} }

func (m *NotifyDelFriendS2C) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 赠送好友体力
type GamerSendFriendEnergyC2S struct {
	// 好友ID（-1表示一键赠送）
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerSendFriendEnergyC2S) Reset()                    { *m = GamerSendFriendEnergyC2S{} }
func (m *GamerSendFriendEnergyC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerSendFriendEnergyC2S) ProtoMessage()               {}
func (*GamerSendFriendEnergyC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{10} }

func (m *GamerSendFriendEnergyC2S) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 赠送好友体力
type GamerSendFriendEnergyS2C struct {
	// 好友ID（-1表示一键赠送）
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerSendFriendEnergyS2C) Reset()                    { *m = GamerSendFriendEnergyS2C{} }
func (m *GamerSendFriendEnergyS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerSendFriendEnergyS2C) ProtoMessage()               {}
func (*GamerSendFriendEnergyS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{11} }

func (m *GamerSendFriendEnergyS2C) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 通知玩家 好友给你赠送了体力
type NotifySendFriendEnergyS2C struct {
	// 给自己赠送体力的好友id
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifySendFriendEnergyS2C) Reset()                    { *m = NotifySendFriendEnergyS2C{} }
func (m *NotifySendFriendEnergyS2C) String() string            { return proto.CompactTextString(m) }
func (*NotifySendFriendEnergyS2C) ProtoMessage()               {}
func (*NotifySendFriendEnergyS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{12} }

func (m *NotifySendFriendEnergyS2C) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 领取好友赠送的体力
type GamerDrawFriendEnergyC2S struct {
	// 好友ID(-1:表示一键领取（只能领取到可领取上限))
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDrawFriendEnergyC2S) Reset()                    { *m = GamerDrawFriendEnergyC2S{} }
func (m *GamerDrawFriendEnergyC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerDrawFriendEnergyC2S) ProtoMessage()               {}
func (*GamerDrawFriendEnergyC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{13} }

func (m *GamerDrawFriendEnergyC2S) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 领取好友赠送的体力
type GamerDrawFriendEnergyS2C struct {
	// 当日已领取体力次数
	EnergyRecvNum *int32 `protobuf:"varint,1,opt,name=energyRecvNum" json:"energyRecvNum,omitempty"`
	// 领取赠送体力的好友id
	RecvIds          []int32 `protobuf:"varint,2,rep,name=recvIds" json:"recvIds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerDrawFriendEnergyS2C) Reset()                    { *m = GamerDrawFriendEnergyS2C{} }
func (m *GamerDrawFriendEnergyS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDrawFriendEnergyS2C) ProtoMessage()               {}
func (*GamerDrawFriendEnergyS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{14} }

func (m *GamerDrawFriendEnergyS2C) GetEnergyRecvNum() int32 {
	if m != nil && m.EnergyRecvNum != nil {
		return *m.EnergyRecvNum
	}
	return 0
}

func (m *GamerDrawFriendEnergyS2C) GetRecvIds() []int32 {
	if m != nil {
		return m.RecvIds
	}
	return nil
}

// 获取好友申请信息
type GamerFriendRequestGetInfoC2S struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerFriendRequestGetInfoC2S) Reset()                    { *m = GamerFriendRequestGetInfoC2S{} }
func (m *GamerFriendRequestGetInfoC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerFriendRequestGetInfoC2S) ProtoMessage()               {}
func (*GamerFriendRequestGetInfoC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{15} }

// 获取好友申请信息
type GamerFriendRequestGetInfoS2C struct {
	// 好友信息
	FrdReqDetails    []*FriendRequestDetail `protobuf:"bytes,2,rep,name=frdReqDetails" json:"frdReqDetails,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *GamerFriendRequestGetInfoS2C) Reset()                    { *m = GamerFriendRequestGetInfoS2C{} }
func (m *GamerFriendRequestGetInfoS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerFriendRequestGetInfoS2C) ProtoMessage()               {}
func (*GamerFriendRequestGetInfoS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{16} }

func (m *GamerFriendRequestGetInfoS2C) GetFrdReqDetails() []*FriendRequestDetail {
	if m != nil {
		return m.FrdReqDetails
	}
	return nil
}

// 获取玩家队伍信息
type GamerGetPlayerTeamInfoC2S struct {
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerGetPlayerTeamInfoC2S) Reset()                    { *m = GamerGetPlayerTeamInfoC2S{} }
func (m *GamerGetPlayerTeamInfoC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerGetPlayerTeamInfoC2S) ProtoMessage()               {}
func (*GamerGetPlayerTeamInfoC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{17} }

func (m *GamerGetPlayerTeamInfoC2S) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 获取玩家队伍信息
type GamerGetPlayerTeamInfoS2C struct {
	// id
	Id *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// icon
	Icon *int32 `protobuf:"varint,2,opt,name=icon" json:"icon,omitempty"`
	// 名称
	Name *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// 等级
	Level *int32 `protobuf:"varint,4,opt,name=level" json:"level,omitempty"`
	// 玩家状态
	State *GamerStatus `protobuf:"varint,5,opt,name=state,enum=GamerStatus" json:"state,omitempty"`
	// 离线时间戳
	OfflineTime *int64 `protobuf:"varint,6,opt,name=offlineTime" json:"offlineTime,omitempty"`
	// 联盟名字
	LeagueName *string `protobuf:"bytes,7,opt,name=leagueName" json:"leagueName,omitempty"`
	// 联盟icon
	AllianceIcon *int32 `protobuf:"varint,8,opt,name=allianceIcon" json:"allianceIcon,omitempty"`
	// 主力
	Starter []*SquadInfo `protobuf:"bytes,9,rep,name=starter" json:"starter,omitempty"`
	// 替补
	Bench []*SquadInfo `protobuf:"bytes,10,rep,name=bench" json:"bench,omitempty"`
	// 战力
	Power            *uint64 `protobuf:"varint,11,opt,name=power" json:"power,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerGetPlayerTeamInfoS2C) Reset()                    { *m = GamerGetPlayerTeamInfoS2C{} }
func (m *GamerGetPlayerTeamInfoS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerGetPlayerTeamInfoS2C) ProtoMessage()               {}
func (*GamerGetPlayerTeamInfoS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{18} }

func (m *GamerGetPlayerTeamInfoS2C) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerGetPlayerTeamInfoS2C) GetIcon() int32 {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return 0
}

func (m *GamerGetPlayerTeamInfoS2C) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GamerGetPlayerTeamInfoS2C) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *GamerGetPlayerTeamInfoS2C) GetState() GamerStatus {
	if m != nil && m.State != nil {
		return *m.State
	}
	return GamerStatus_offline
}

func (m *GamerGetPlayerTeamInfoS2C) GetOfflineTime() int64 {
	if m != nil && m.OfflineTime != nil {
		return *m.OfflineTime
	}
	return 0
}

func (m *GamerGetPlayerTeamInfoS2C) GetLeagueName() string {
	if m != nil && m.LeagueName != nil {
		return *m.LeagueName
	}
	return ""
}

func (m *GamerGetPlayerTeamInfoS2C) GetAllianceIcon() int32 {
	if m != nil && m.AllianceIcon != nil {
		return *m.AllianceIcon
	}
	return 0
}

func (m *GamerGetPlayerTeamInfoS2C) GetStarter() []*SquadInfo {
	if m != nil {
		return m.Starter
	}
	return nil
}

func (m *GamerGetPlayerTeamInfoS2C) GetBench() []*SquadInfo {
	if m != nil {
		return m.Bench
	}
	return nil
}

func (m *GamerGetPlayerTeamInfoS2C) GetPower() uint64 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

// 处理好友申请
type GamerDealFriendRequestC2S struct {
	// 好友id（-1:操作全部）
	Id *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// 同意/拒绝
	IsAgree          *bool  `protobuf:"varint,2,opt,name=isAgree" json:"isAgree,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDealFriendRequestC2S) Reset()                    { *m = GamerDealFriendRequestC2S{} }
func (m *GamerDealFriendRequestC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerDealFriendRequestC2S) ProtoMessage()               {}
func (*GamerDealFriendRequestC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{19} }

func (m *GamerDealFriendRequestC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerDealFriendRequestC2S) GetIsAgree() bool {
	if m != nil && m.IsAgree != nil {
		return *m.IsAgree
	}
	return false
}

// 处理好友申请
type GamerDealFriendRequestS2C struct {
	// 好友id
	Id *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// 是否同意
	IsAgree *bool `protobuf:"varint,2,opt,name=isAgree" json:"isAgree,omitempty"`
	// 好友信息
	FrdDetail        []*FriendDetail `protobuf:"bytes,3,rep,name=frdDetail" json:"frdDetail,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GamerDealFriendRequestS2C) Reset()                    { *m = GamerDealFriendRequestS2C{} }
func (m *GamerDealFriendRequestS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDealFriendRequestS2C) ProtoMessage()               {}
func (*GamerDealFriendRequestS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{20} }

func (m *GamerDealFriendRequestS2C) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerDealFriendRequestS2C) GetIsAgree() bool {
	if m != nil && m.IsAgree != nil {
		return *m.IsAgree
	}
	return false
}

func (m *GamerDealFriendRequestS2C) GetFrdDetail() []*FriendDetail {
	if m != nil {
		return m.FrdDetail
	}
	return nil
}

// 通知玩家、申请的好友已同意加你为好友
type NotifyDealFriendRequestS2C struct {
	// 好友信息
	FrdDetail        *FriendDetail `protobuf:"bytes,1,opt,name=frdDetail" json:"frdDetail,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *NotifyDealFriendRequestS2C) Reset()                    { *m = NotifyDealFriendRequestS2C{} }
func (m *NotifyDealFriendRequestS2C) String() string            { return proto.CompactTextString(m) }
func (*NotifyDealFriendRequestS2C) ProtoMessage()               {}
func (*NotifyDealFriendRequestS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{21} }

func (m *NotifyDealFriendRequestS2C) GetFrdDetail() *FriendDetail {
	if m != nil {
		return m.FrdDetail
	}
	return nil
}

// 添加黑名单
type GamerAddBackListC2S struct {
	// 玩家ID
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerAddBackListC2S) Reset()                    { *m = GamerAddBackListC2S{} }
func (m *GamerAddBackListC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerAddBackListC2S) ProtoMessage()               {}
func (*GamerAddBackListC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{22} }

func (m *GamerAddBackListC2S) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 添加黑名单
type GamerAddBackListS2C struct {
	// 黑名单信息
	FrdDetail        *FriendDetail `protobuf:"bytes,1,opt,name=frdDetail" json:"frdDetail,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerAddBackListS2C) Reset()                    { *m = GamerAddBackListS2C{} }
func (m *GamerAddBackListS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerAddBackListS2C) ProtoMessage()               {}
func (*GamerAddBackListS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{23} }

func (m *GamerAddBackListS2C) GetFrdDetail() *FriendDetail {
	if m != nil {
		return m.FrdDetail
	}
	return nil
}

// 删除黑名单
type GamerDelBackListC2S struct {
	// 玩家ID
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelBackListC2S) Reset()                    { *m = GamerDelBackListC2S{} }
func (m *GamerDelBackListC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerDelBackListC2S) ProtoMessage()               {}
func (*GamerDelBackListC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{24} }

func (m *GamerDelBackListC2S) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 删除黑名单
type GamerDelBackListS2C struct {
	// 玩家ID
	FriendId         *int32 `protobuf:"varint,1,opt,name=friendId" json:"friendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelBackListS2C) Reset()                    { *m = GamerDelBackListS2C{} }
func (m *GamerDelBackListS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDelBackListS2C) ProtoMessage()               {}
func (*GamerDelBackListS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{25} }

func (m *GamerDelBackListS2C) GetFriendId() int32 {
	if m != nil && m.FriendId != nil {
		return *m.FriendId
	}
	return 0
}

// 获取黑名单
type GamerGetBackListInfoC2S struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerGetBackListInfoC2S) Reset()                    { *m = GamerGetBackListInfoC2S{} }
func (m *GamerGetBackListInfoC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerGetBackListInfoC2S) ProtoMessage()               {}
func (*GamerGetBackListInfoC2S) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{26} }

// 获取黑名单
type GamerGetBackListInfoS2C struct {
	// 黑名单信息
	FrdDetails       []*FriendDetail `protobuf:"bytes,1,rep,name=frdDetails" json:"frdDetails,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GamerGetBackListInfoS2C) Reset()                    { *m = GamerGetBackListInfoS2C{} }
func (m *GamerGetBackListInfoS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerGetBackListInfoS2C) ProtoMessage()               {}
func (*GamerGetBackListInfoS2C) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{27} }

func (m *GamerGetBackListInfoS2C) GetFrdDetails() []*FriendDetail {
	if m != nil {
		return m.FrdDetails
	}
	return nil
}

// 提示好友改名、icon
type GamerInformFriendNameChangedS2C struct {
	// 我的id
	Id *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// 我的新名字
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 我的icon
	TeamIcon         *int32 `protobuf:"varint,3,opt,name=teamIcon" json:"teamIcon,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerInformFriendNameChangedS2C) Reset()         { *m = GamerInformFriendNameChangedS2C{} }
func (m *GamerInformFriendNameChangedS2C) String() string { return proto.CompactTextString(m) }
func (*GamerInformFriendNameChangedS2C) ProtoMessage()    {}
func (*GamerInformFriendNameChangedS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor27, []int{28}
}

func (m *GamerInformFriendNameChangedS2C) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerInformFriendNameChangedS2C) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GamerInformFriendNameChangedS2C) GetTeamIcon() int32 {
	if m != nil && m.TeamIcon != nil {
		return *m.TeamIcon
	}
	return 0
}

func init() {
	proto.RegisterType((*GamerFriendGetInfoC2S)(nil), "GamerFriendGetInfoC2S")
	proto.RegisterType((*GamerFriendGetInfoS2C)(nil), "GamerFriendGetInfoS2C")
	proto.RegisterType((*GamerFindFriendC2S)(nil), "GamerFindFriendC2S")
	proto.RegisterType((*GamerFindFriendS2C)(nil), "GamerFindFriendS2C")
	proto.RegisterType((*GamerAddFriendC2S)(nil), "GamerAddFriendC2S")
	proto.RegisterType((*GamerAddFriendS2C)(nil), "GamerAddFriendS2C")
	proto.RegisterType((*NotifyAddFriendRequestS2C)(nil), "NotifyAddFriendRequestS2C")
	proto.RegisterType((*GamerDelFriendC2S)(nil), "GamerDelFriendC2S")
	proto.RegisterType((*GamerDelFriendS2C)(nil), "GamerDelFriendS2C")
	proto.RegisterType((*NotifyDelFriendS2C)(nil), "NotifyDelFriendS2C")
	proto.RegisterType((*GamerSendFriendEnergyC2S)(nil), "GamerSendFriendEnergyC2S")
	proto.RegisterType((*GamerSendFriendEnergyS2C)(nil), "GamerSendFriendEnergyS2C")
	proto.RegisterType((*NotifySendFriendEnergyS2C)(nil), "NotifySendFriendEnergyS2C")
	proto.RegisterType((*GamerDrawFriendEnergyC2S)(nil), "GamerDrawFriendEnergyC2S")
	proto.RegisterType((*GamerDrawFriendEnergyS2C)(nil), "GamerDrawFriendEnergyS2C")
	proto.RegisterType((*GamerFriendRequestGetInfoC2S)(nil), "GamerFriendRequestGetInfoC2S")
	proto.RegisterType((*GamerFriendRequestGetInfoS2C)(nil), "GamerFriendRequestGetInfoS2C")
	proto.RegisterType((*GamerGetPlayerTeamInfoC2S)(nil), "GamerGetPlayerTeamInfoC2S")
	proto.RegisterType((*GamerGetPlayerTeamInfoS2C)(nil), "GamerGetPlayerTeamInfoS2C")
	proto.RegisterType((*GamerDealFriendRequestC2S)(nil), "GamerDealFriendRequestC2S")
	proto.RegisterType((*GamerDealFriendRequestS2C)(nil), "GamerDealFriendRequestS2C")
	proto.RegisterType((*NotifyDealFriendRequestS2C)(nil), "NotifyDealFriendRequestS2C")
	proto.RegisterType((*GamerAddBackListC2S)(nil), "GamerAddBackListC2S")
	proto.RegisterType((*GamerAddBackListS2C)(nil), "GamerAddBackListS2C")
	proto.RegisterType((*GamerDelBackListC2S)(nil), "GamerDelBackListC2S")
	proto.RegisterType((*GamerDelBackListS2C)(nil), "GamerDelBackListS2C")
	proto.RegisterType((*GamerGetBackListInfoC2S)(nil), "GamerGetBackListInfoC2S")
	proto.RegisterType((*GamerGetBackListInfoS2C)(nil), "GamerGetBackListInfoS2C")
	proto.RegisterType((*GamerInformFriendNameChangedS2C)(nil), "GamerInformFriendNameChangedS2C")
	proto.RegisterEnum("GamerFriendGetInfoC2S_MsgID", GamerFriendGetInfoC2S_MsgID_name, GamerFriendGetInfoC2S_MsgID_value)
	proto.RegisterEnum("GamerFriendGetInfoS2C_MsgID", GamerFriendGetInfoS2C_MsgID_name, GamerFriendGetInfoS2C_MsgID_value)
	proto.RegisterEnum("GamerFindFriendC2S_MsgID", GamerFindFriendC2S_MsgID_name, GamerFindFriendC2S_MsgID_value)
	proto.RegisterEnum("GamerFindFriendS2C_MsgID", GamerFindFriendS2C_MsgID_name, GamerFindFriendS2C_MsgID_value)
	proto.RegisterEnum("GamerAddFriendC2S_MsgID", GamerAddFriendC2S_MsgID_name, GamerAddFriendC2S_MsgID_value)
	proto.RegisterEnum("GamerAddFriendS2C_MsgID", GamerAddFriendS2C_MsgID_name, GamerAddFriendS2C_MsgID_value)
	proto.RegisterEnum("NotifyAddFriendRequestS2C_MsgID", NotifyAddFriendRequestS2C_MsgID_name, NotifyAddFriendRequestS2C_MsgID_value)
	proto.RegisterEnum("GamerDelFriendC2S_MsgID", GamerDelFriendC2S_MsgID_name, GamerDelFriendC2S_MsgID_value)
	proto.RegisterEnum("GamerDelFriendS2C_MsgID", GamerDelFriendS2C_MsgID_name, GamerDelFriendS2C_MsgID_value)
	proto.RegisterEnum("NotifyDelFriendS2C_MsgID", NotifyDelFriendS2C_MsgID_name, NotifyDelFriendS2C_MsgID_value)
	proto.RegisterEnum("GamerSendFriendEnergyC2S_MsgID", GamerSendFriendEnergyC2S_MsgID_name, GamerSendFriendEnergyC2S_MsgID_value)
	proto.RegisterEnum("GamerSendFriendEnergyS2C_MsgID", GamerSendFriendEnergyS2C_MsgID_name, GamerSendFriendEnergyS2C_MsgID_value)
	proto.RegisterEnum("NotifySendFriendEnergyS2C_MsgID", NotifySendFriendEnergyS2C_MsgID_name, NotifySendFriendEnergyS2C_MsgID_value)
	proto.RegisterEnum("GamerDrawFriendEnergyC2S_MsgID", GamerDrawFriendEnergyC2S_MsgID_name, GamerDrawFriendEnergyC2S_MsgID_value)
	proto.RegisterEnum("GamerDrawFriendEnergyS2C_MsgID", GamerDrawFriendEnergyS2C_MsgID_name, GamerDrawFriendEnergyS2C_MsgID_value)
	proto.RegisterEnum("GamerFriendRequestGetInfoC2S_MsgID", GamerFriendRequestGetInfoC2S_MsgID_name, GamerFriendRequestGetInfoC2S_MsgID_value)
	proto.RegisterEnum("GamerFriendRequestGetInfoS2C_MsgID", GamerFriendRequestGetInfoS2C_MsgID_name, GamerFriendRequestGetInfoS2C_MsgID_value)
	proto.RegisterEnum("GamerGetPlayerTeamInfoC2S_MsgID", GamerGetPlayerTeamInfoC2S_MsgID_name, GamerGetPlayerTeamInfoC2S_MsgID_value)
	proto.RegisterEnum("GamerGetPlayerTeamInfoS2C_MsgID", GamerGetPlayerTeamInfoS2C_MsgID_name, GamerGetPlayerTeamInfoS2C_MsgID_value)
	proto.RegisterEnum("GamerDealFriendRequestC2S_MsgID", GamerDealFriendRequestC2S_MsgID_name, GamerDealFriendRequestC2S_MsgID_value)
	proto.RegisterEnum("GamerDealFriendRequestS2C_MsgID", GamerDealFriendRequestS2C_MsgID_name, GamerDealFriendRequestS2C_MsgID_value)
	proto.RegisterEnum("NotifyDealFriendRequestS2C_MsgID", NotifyDealFriendRequestS2C_MsgID_name, NotifyDealFriendRequestS2C_MsgID_value)
	proto.RegisterEnum("GamerAddBackListC2S_MsgID", GamerAddBackListC2S_MsgID_name, GamerAddBackListC2S_MsgID_value)
	proto.RegisterEnum("GamerAddBackListS2C_MsgID", GamerAddBackListS2C_MsgID_name, GamerAddBackListS2C_MsgID_value)
	proto.RegisterEnum("GamerDelBackListC2S_MsgID", GamerDelBackListC2S_MsgID_name, GamerDelBackListC2S_MsgID_value)
	proto.RegisterEnum("GamerDelBackListS2C_MsgID", GamerDelBackListS2C_MsgID_name, GamerDelBackListS2C_MsgID_value)
	proto.RegisterEnum("GamerGetBackListInfoC2S_MsgID", GamerGetBackListInfoC2S_MsgID_name, GamerGetBackListInfoC2S_MsgID_value)
	proto.RegisterEnum("GamerGetBackListInfoS2C_MsgID", GamerGetBackListInfoS2C_MsgID_name, GamerGetBackListInfoS2C_MsgID_value)
	proto.RegisterEnum("GamerInformFriendNameChangedS2C_MsgID", GamerInformFriendNameChangedS2C_MsgID_name, GamerInformFriendNameChangedS2C_MsgID_value)
}

func init() { proto.RegisterFile("friend.proto", fileDescriptor27) }

var fileDescriptor27 = []byte{
	// 772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x55, 0x92, 0xa6, 0x6d, 0x6e, 0x26, 0xd0, 0xba, 0xad, 0x70, 0x0b, 0x12, 0xc5, 0xab, 0x0a,
	0x44, 0x90, 0x22, 0x76, 0xa8, 0x8b, 0x36, 0x81, 0x2a, 0x12, 0x8d, 0x50, 0x53, 0x24, 0xd8, 0x20,
	0x0d, 0xf6, 0x75, 0x6a, 0xd5, 0x8f, 0x76, 0xec, 0xb4, 0x64, 0xc9, 0xbb, 0xa8, 0xb0, 0xe4, 0x57,
	0x78, 0xfc, 0x1a, 0x2b, 0x66, 0xc6, 0x76, 0xc8, 0x63, 0x1c, 0x0c, 0xbb, 0x8c, 0x3d, 0xe7, 0xdc,
	0x73, 0x5f, 0xc7, 0x01, 0x62, 0x33, 0x07, 0x7d, 0xab, 0x7e, 0xc2, 0x82, 0x28, 0xd8, 0xa8, 0x7a,
	0xd4, 0x64, 0x41, 0x72, 0x20, 0x66, 0xe0, 0x79, 0x81, 0x1f, 0x9f, 0x8c, 0xbb, 0xb0, 0xb6, 0x47,
	0x3d, 0x64, 0x8f, 0xe4, 0xfd, 0x3d, 0x8c, 0xda, 0xbe, 0x1d, 0x34, 0x1b, 0x5d, 0x63, 0x15, 0xca,
	0xfb, 0x61, 0xaf, 0xdd, 0xd2, 0xaa, 0x30, 0x8f, 0xf2, 0xd7, 0xd2, 0x6b, 0x62, 0xf4, 0x54, 0xd7,
	0xbb, 0x8d, 0xa6, 0xb6, 0x06, 0x35, 0xf4, 0x91, 0xf5, 0x06, 0x07, 0x68, 0x9e, 0x75, 0xfa, 0x9e,
	0x5e, 0xd8, 0x2c, 0x6c, 0x95, 0xb5, 0x5b, 0x00, 0x36, 0xb3, 0x5a, 0x18, 0x51, 0xc7, 0x0d, 0xf5,
	0xe2, 0x66, 0x69, 0xab, 0xda, 0xa8, 0xd5, 0x63, 0x74, 0xfc, 0x34, 0x23, 0xd0, 0x73, 0xd0, 0xe2,
	0x40, 0x8e, 0x6f, 0xc5, 0xd7, 0xb9, 0x28, 0x7e, 0xa5, 0x74, 0x8c, 0x03, 0xc9, 0x5d, 0xd1, 0x96,
	0xa1, 0xc2, 0x50, 0x24, 0xc3, 0x5f, 0x72, 0xea, 0xc2, 0xd6, 0xa2, 0x56, 0x83, 0x72, 0x18, 0x51,
	0x16, 0xe9, 0x25, 0x11, 0x5d, 0x45, 0xfd, 0x86, 0x18, 0x17, 0x85, 0x29, 0x6e, 0x91, 0xc1, 0xb8,
	0xd4, 0x82, 0x42, 0xaa, 0xb6, 0x02, 0x55, 0x86, 0x36, 0xb2, 0xf0, 0xe8, 0xd0, 0xf1, 0x50, 0xc6,
	0x2c, 0x0b, 0x19, 0x3e, 0xbe, 0x8a, 0xba, 0x7f, 0xe2, 0x8e, 0x2b, 0x9b, 0x13, 0xca, 0x32, 0xa4,
	0x3c, 0x80, 0x65, 0xa9, 0x64, 0xc7, 0x1a, 0x49, 0x72, 0x09, 0x16, 0xe3, 0xee, 0xb5, 0x2d, 0x29,
	0x43, 0x99, 0xc7, 0x5b, 0x05, 0x58, 0x64, 0x91, 0x17, 0xfc, 0x02, 0xd6, 0x3b, 0x41, 0xe4, 0xd8,
	0x83, 0x21, 0xfa, 0x00, 0x4f, 0xfb, 0x18, 0x46, 0x82, 0xe4, 0xb6, 0x98, 0x1f, 0xf1, 0x20, 0xce,
	0x5b, 0x26, 0x5a, 0x6d, 0xac, 0xd6, 0xc7, 0x2e, 0x26, 0xed, 0x5b, 0x4b, 0xe9, 0xc9, 0x90, 0xfe,
	0xdb, 0xaf, 0xd2, 0x50, 0x5c, 0x0b, 0xdd, 0xac, 0xcc, 0x32, 0x3a, 0xf4, 0x8e, 0x4c, 0x83, 0x27,
	0x33, 0x2b, 0xce, 0x00, 0x6f, 0x83, 0x16, 0x67, 0xf6, 0x17, 0xb4, 0x42, 0xf8, 0x0f, 0x2e, 0x7c,
	0x17, 0x74, 0x19, 0xbb, 0x8b, 0xe9, 0x70, 0x3c, 0x94, 0x73, 0x9d, 0x5b, 0xff, 0x7b, 0x92, 0xc9,
	0x31, 0xdd, 0xa0, 0x6c, 0x8e, 0x56, 0xda, 0xa0, 0x7c, 0x24, 0x8a, 0x6c, 0x7e, 0x8e, 0x64, 0xd3,
	0x62, 0xf4, 0xfc, 0xbf, 0xb2, 0xf9, 0x40, 0x8c, 0x67, 0x19, 0x1c, 0x33, 0xd6, 0xfe, 0x2a, 0x2c,
	0xf0, 0x05, 0x38, 0x6b, 0x5b, 0xf1, 0xce, 0x67, 0x31, 0xdf, 0x87, 0x1b, 0x23, 0x6e, 0x92, 0xcc,
	0xd5, 0x6c, 0x0f, 0xfa, 0x48, 0x0c, 0x3a, 0x03, 0x25, 0x34, 0xdd, 0x81, 0xda, 0xe8, 0xf4, 0xa6,
	0xb6, 0xa3, 0x1e, 0x5f, 0x75, 0x88, 0x26, 0xac, 0xcb, 0x10, 0x9c, 0xf5, 0x89, 0x4b, 0x07, 0xc8,
	0x0e, 0x91, 0x7a, 0x89, 0xaa, 0x7c, 0x75, 0xbb, 0x20, 0xc6, 0x65, 0x31, 0x8b, 0x45, 0xa8, 0x04,
	0x28, 0x3a, 0x09, 0x9e, 0xf7, 0x6c, 0xce, 0x31, 0x03, 0x3f, 0x31, 0x14, 0x7e, 0xf2, 0x39, 0x4c,
	0x7a, 0x49, 0x45, 0x58, 0x9a, 0x8b, 0x67, 0xe8, 0x4a, 0x1f, 0x29, 0x6b, 0xd7, 0xa5, 0xc3, 0x45,
	0xa8, 0x97, 0xf9, 0xf1, 0x4a, 0x83, 0xd4, 0xe3, 0x41, 0xe3, 0x8f, 0xfa, 0xa1, 0xf0, 0xa7, 0xc0,
	0xb6, 0x5d, 0xc7, 0x47, 0xe9, 0x4f, 0xf3, 0xfc, 0x4a, 0x49, 0xe3, 0x91, 0x5c, 0xa4, 0xbd, 0x3e,
	0x76, 0x04, 0xe9, 0x82, 0x24, 0x5d, 0x05, 0x42, 0x5d, 0xd7, 0xa1, 0xbe, 0x89, 0x6d, 0x11, 0x78,
	0x31, 0xe1, 0x5e, 0x90, 0xee, 0x89, 0x4c, 0xaf, 0xc8, 0x92, 0x41, 0xbd, 0x7b, 0xda, 0xa7, 0x96,
	0x90, 0xac, 0xad, 0x43, 0xf9, 0x25, 0xfa, 0xe6, 0x91, 0x0e, 0x53, 0xaf, 0xb8, 0xc4, 0x93, 0xe0,
	0x9c, 0xa3, 0xaa, 0x9c, 0x66, 0x2e, 0xa3, 0x1a, 0x9d, 0xa4, 0x18, 0x2d, 0xa4, 0xee, 0x58, 0x23,
	0x44, 0x49, 0x47, 0x8b, 0xc1, 0x67, 0xc7, 0x09, 0x77, 0x7a, 0x0c, 0x63, 0x83, 0x55, 0x5a, 0xe7,
	0x27, 0x62, 0x9c, 0x64, 0xf1, 0x4d, 0x16, 0x77, 0x92, 0x4f, 0xdb, 0x84, 0xca, 0xd0, 0xe8, 0x79,
	0x91, 0xf3, 0x7d, 0x92, 0x78, 0xc4, 0xa7, 0xb0, 0x91, 0x1a, 0x8b, 0x22, 0xe4, 0x18, 0x6b, 0x41,
	0x1a, 0xe6, 0x04, 0xab, 0x62, 0x45, 0xbf, 0xf3, 0x15, 0xdd, 0x86, 0x95, 0xd4, 0xc6, 0x77, 0xa9,
	0x79, 0xfc, 0xd8, 0x89, 0x4b, 0x92, 0x6b, 0xca, 0x2e, 0x89, 0xb1, 0x3f, 0x0d, 0xcf, 0x27, 0x47,
	0x4d, 0x97, 0xaa, 0xe1, 0xe6, 0xf9, 0xcf, 0x6a, 0x3e, 0x2b, 0xe1, 0xb9, 0x4d, 0x8f, 0xc3, 0xef,
	0xc1, 0xb5, 0x74, 0x63, 0x52, 0xf8, 0x0c, 0x2f, 0xf8, 0x42, 0x8c, 0x03, 0x35, 0x20, 0xdf, 0xf7,
	0x3c, 0x83, 0xd3, 0x84, 0x9b, 0x92, 0x53, 0x10, 0x31, 0x2f, 0x06, 0x88, 0xdd, 0x69, 0x1e, 0x51,
	0xbf, 0x87, 0x96, 0x62, 0x79, 0xe5, 0xba, 0x16, 0xe5, 0x66, 0xf1, 0x4c, 0x23, 0xb1, 0xe5, 0x62,
	0xab, 0x32, 0xff, 0x84, 0x7c, 0x25, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x60, 0x69, 0xb6, 0x18,
	0xa1, 0x09, 0x00, 0x00,
}
