// Code generated by protoc-gen-go.
// source: gm.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// gm修改玩家等级
type GmSetGamerLvRequest struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Lv               *int32 `protobuf:"varint,2,opt,name=lv" json:"lv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GmSetGamerLvRequest) Reset()                    { *m = GmSetGamerLvRequest{} }
func (m *GmSetGamerLvRequest) String() string            { return proto.CompactTextString(m) }
func (*GmSetGamerLvRequest) ProtoMessage()               {}
func (*GmSetGamerLvRequest) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{0} }

func (m *GmSetGamerLvRequest) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GmSetGamerLvRequest) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

// gm修改玩家名称
type GmSetGamerNameRequest struct {
	Gid              *int32  `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GmSetGamerNameRequest) Reset()                    { *m = GmSetGamerNameRequest{} }
func (m *GmSetGamerNameRequest) String() string            { return proto.CompactTextString(m) }
func (*GmSetGamerNameRequest) ProtoMessage()               {}
func (*GmSetGamerNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{1} }

func (m *GmSetGamerNameRequest) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GmSetGamerNameRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

// 设置进程禁止登录
type GmSetServerForbidLogin struct {
	IsForbidLogin    *bool  `protobuf:"varint,1,opt,name=isForbidLogin" json:"isForbidLogin,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GmSetServerForbidLogin) Reset()                    { *m = GmSetServerForbidLogin{} }
func (m *GmSetServerForbidLogin) String() string            { return proto.CompactTextString(m) }
func (*GmSetServerForbidLogin) ProtoMessage()               {}
func (*GmSetServerForbidLogin) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{2} }

func (m *GmSetServerForbidLogin) GetIsForbidLogin() bool {
	if m != nil && m.IsForbidLogin != nil {
		return *m.IsForbidLogin
	}
	return false
}

func init() {
	proto.RegisterType((*GmSetGamerLvRequest)(nil), "GmSetGamerLvRequest")
	proto.RegisterType((*GmSetGamerNameRequest)(nil), "GmSetGamerNameRequest")
	proto.RegisterType((*GmSetServerForbidLogin)(nil), "GmSetServerForbidLogin")
}

func init() { proto.RegisterFile("gm.proto", fileDescriptor30) }

var fileDescriptor30 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0xcf, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe3, 0x12, 0x76, 0xcf, 0x0d, 0x4e, 0x2d, 0x71, 0x4f, 0xcc,
	0x4d, 0x2d, 0xf2, 0x29, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe6, 0x62, 0x4e,
	0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x15, 0xe2, 0xe2, 0x62, 0xca, 0x29, 0x93, 0x60,
	0x02, 0xb1, 0x95, 0x8c, 0xb8, 0x44, 0x11, 0xea, 0xfd, 0x80, 0x04, 0x56, 0x1d, 0x3c, 0x5c, 0x2c,
	0x79, 0x40, 0x39, 0xb0, 0x1e, 0x4e, 0x25, 0x7d, 0x2e, 0x31, 0xb0, 0x9e, 0xe0, 0xd4, 0xa2, 0xb2,
	0xd4, 0x22, 0xb7, 0xfc, 0xa2, 0xa4, 0xcc, 0x14, 0x9f, 0xfc, 0xf4, 0xcc, 0x3c, 0x21, 0x51, 0x2e,
	0xde, 0xcc, 0x62, 0x24, 0x01, 0xb0, 0x76, 0x0e, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x41,
	0x10, 0x82, 0x9f, 0x00, 0x00, 0x00,
}
