// Code generated by protoc-gen-go.
// source: legend.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LegendGetDataC2S_MsgID int32

const (
	LegendGetDataC2S_eMsgID LegendGetDataC2S_MsgID = 14346
)

var LegendGetDataC2S_MsgID_name = map[int32]string{
	14346: "eMsgID",
}
var LegendGetDataC2S_MsgID_value = map[string]int32{
	"eMsgID": 14346,
}

func (x LegendGetDataC2S_MsgID) Enum() *LegendGetDataC2S_MsgID {
	p := new(LegendGetDataC2S_MsgID)
	*p = x
	return p
}
func (x LegendGetDataC2S_MsgID) String() string {
	return proto.EnumName(LegendGetDataC2S_MsgID_name, int32(x))
}
func (x *LegendGetDataC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendGetDataC2S_MsgID_value, data, "LegendGetDataC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendGetDataC2S_MsgID(value)
	return nil
}
func (LegendGetDataC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{2, 0} }

type LegendGetDataS2C_MsgID int32

const (
	LegendGetDataS2C_eMsgID LegendGetDataS2C_MsgID = 14346
)

var LegendGetDataS2C_MsgID_name = map[int32]string{
	14346: "eMsgID",
}
var LegendGetDataS2C_MsgID_value = map[string]int32{
	"eMsgID": 14346,
}

func (x LegendGetDataS2C_MsgID) Enum() *LegendGetDataS2C_MsgID {
	p := new(LegendGetDataS2C_MsgID)
	*p = x
	return p
}
func (x LegendGetDataS2C_MsgID) String() string {
	return proto.EnumName(LegendGetDataS2C_MsgID_name, int32(x))
}
func (x *LegendGetDataS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendGetDataS2C_MsgID_value, data, "LegendGetDataS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendGetDataS2C_MsgID(value)
	return nil
}
func (LegendGetDataS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{3, 0} }

type LegendUnlockC2S_MsgID int32

const (
	LegendUnlockC2S_eMsgID LegendUnlockC2S_MsgID = 14347
)

var LegendUnlockC2S_MsgID_name = map[int32]string{
	14347: "eMsgID",
}
var LegendUnlockC2S_MsgID_value = map[string]int32{
	"eMsgID": 14347,
}

func (x LegendUnlockC2S_MsgID) Enum() *LegendUnlockC2S_MsgID {
	p := new(LegendUnlockC2S_MsgID)
	*p = x
	return p
}
func (x LegendUnlockC2S_MsgID) String() string {
	return proto.EnumName(LegendUnlockC2S_MsgID_name, int32(x))
}
func (x *LegendUnlockC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendUnlockC2S_MsgID_value, data, "LegendUnlockC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendUnlockC2S_MsgID(value)
	return nil
}
func (LegendUnlockC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{4, 0} }

type LegendUnlockS2C_MsgID int32

const (
	LegendUnlockS2C_eMsgID LegendUnlockS2C_MsgID = 14347
)

var LegendUnlockS2C_MsgID_name = map[int32]string{
	14347: "eMsgID",
}
var LegendUnlockS2C_MsgID_value = map[string]int32{
	"eMsgID": 14347,
}

func (x LegendUnlockS2C_MsgID) Enum() *LegendUnlockS2C_MsgID {
	p := new(LegendUnlockS2C_MsgID)
	*p = x
	return p
}
func (x LegendUnlockS2C_MsgID) String() string {
	return proto.EnumName(LegendUnlockS2C_MsgID_name, int32(x))
}
func (x *LegendUnlockS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendUnlockS2C_MsgID_value, data, "LegendUnlockS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendUnlockS2C_MsgID(value)
	return nil
}
func (LegendUnlockS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{5, 0} }

type LegendUnlockFieldS2C_MsgID int32

const (
	LegendUnlockFieldS2C_eMsgID LegendUnlockFieldS2C_MsgID = 14348
)

var LegendUnlockFieldS2C_MsgID_name = map[int32]string{
	14348: "eMsgID",
}
var LegendUnlockFieldS2C_MsgID_value = map[string]int32{
	"eMsgID": 14348,
}

func (x LegendUnlockFieldS2C_MsgID) Enum() *LegendUnlockFieldS2C_MsgID {
	p := new(LegendUnlockFieldS2C_MsgID)
	*p = x
	return p
}
func (x LegendUnlockFieldS2C_MsgID) String() string {
	return proto.EnumName(LegendUnlockFieldS2C_MsgID_name, int32(x))
}
func (x *LegendUnlockFieldS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendUnlockFieldS2C_MsgID_value, data, "LegendUnlockFieldS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendUnlockFieldS2C_MsgID(value)
	return nil
}
func (LegendUnlockFieldS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{6, 0}
}

type LegendPlayC2S_MsgID int32

const (
	LegendPlayC2S_eMsgID LegendPlayC2S_MsgID = 14349
)

var LegendPlayC2S_MsgID_name = map[int32]string{
	14349: "eMsgID",
}
var LegendPlayC2S_MsgID_value = map[string]int32{
	"eMsgID": 14349,
}

func (x LegendPlayC2S_MsgID) Enum() *LegendPlayC2S_MsgID {
	p := new(LegendPlayC2S_MsgID)
	*p = x
	return p
}
func (x LegendPlayC2S_MsgID) String() string {
	return proto.EnumName(LegendPlayC2S_MsgID_name, int32(x))
}
func (x *LegendPlayC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendPlayC2S_MsgID_value, data, "LegendPlayC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendPlayC2S_MsgID(value)
	return nil
}
func (LegendPlayC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{8, 0} }

type LegendPlayS2C_MsgID int32

const (
	LegendPlayS2C_eMsgID LegendPlayS2C_MsgID = 14349
)

var LegendPlayS2C_MsgID_name = map[int32]string{
	14349: "eMsgID",
}
var LegendPlayS2C_MsgID_value = map[string]int32{
	"eMsgID": 14349,
}

func (x LegendPlayS2C_MsgID) Enum() *LegendPlayS2C_MsgID {
	p := new(LegendPlayS2C_MsgID)
	*p = x
	return p
}
func (x LegendPlayS2C_MsgID) String() string {
	return proto.EnumName(LegendPlayS2C_MsgID_name, int32(x))
}
func (x *LegendPlayS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendPlayS2C_MsgID_value, data, "LegendPlayS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendPlayS2C_MsgID(value)
	return nil
}
func (LegendPlayS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{9, 0} }

type LegendLevelCultivateC2S_MsgID int32

const (
	LegendLevelCultivateC2S_eMsgID LegendLevelCultivateC2S_MsgID = 14350
)

var LegendLevelCultivateC2S_MsgID_name = map[int32]string{
	14350: "eMsgID",
}
var LegendLevelCultivateC2S_MsgID_value = map[string]int32{
	"eMsgID": 14350,
}

func (x LegendLevelCultivateC2S_MsgID) Enum() *LegendLevelCultivateC2S_MsgID {
	p := new(LegendLevelCultivateC2S_MsgID)
	*p = x
	return p
}
func (x LegendLevelCultivateC2S_MsgID) String() string {
	return proto.EnumName(LegendLevelCultivateC2S_MsgID_name, int32(x))
}
func (x *LegendLevelCultivateC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendLevelCultivateC2S_MsgID_value, data, "LegendLevelCultivateC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendLevelCultivateC2S_MsgID(value)
	return nil
}
func (LegendLevelCultivateC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{10, 0}
}

type LegendLevelCultivateS2C_MsgID int32

const (
	LegendLevelCultivateS2C_eMsgID LegendLevelCultivateS2C_MsgID = 14350
)

var LegendLevelCultivateS2C_MsgID_name = map[int32]string{
	14350: "eMsgID",
}
var LegendLevelCultivateS2C_MsgID_value = map[string]int32{
	"eMsgID": 14350,
}

func (x LegendLevelCultivateS2C_MsgID) Enum() *LegendLevelCultivateS2C_MsgID {
	p := new(LegendLevelCultivateS2C_MsgID)
	*p = x
	return p
}
func (x LegendLevelCultivateS2C_MsgID) String() string {
	return proto.EnumName(LegendLevelCultivateS2C_MsgID_name, int32(x))
}
func (x *LegendLevelCultivateS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendLevelCultivateS2C_MsgID_value, data, "LegendLevelCultivateS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendLevelCultivateS2C_MsgID(value)
	return nil
}
func (LegendLevelCultivateS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{11, 0}
}

type LegendLevelUpC2S_MsgID int32

const (
	LegendLevelUpC2S_eMsgID LegendLevelUpC2S_MsgID = 14351
)

var LegendLevelUpC2S_MsgID_name = map[int32]string{
	14351: "eMsgID",
}
var LegendLevelUpC2S_MsgID_value = map[string]int32{
	"eMsgID": 14351,
}

func (x LegendLevelUpC2S_MsgID) Enum() *LegendLevelUpC2S_MsgID {
	p := new(LegendLevelUpC2S_MsgID)
	*p = x
	return p
}
func (x LegendLevelUpC2S_MsgID) String() string {
	return proto.EnumName(LegendLevelUpC2S_MsgID_name, int32(x))
}
func (x *LegendLevelUpC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendLevelUpC2S_MsgID_value, data, "LegendLevelUpC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendLevelUpC2S_MsgID(value)
	return nil
}
func (LegendLevelUpC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{12, 0} }

type LegendLevelUpS2C_MsgID int32

const (
	LegendLevelUpS2C_eMsgID LegendLevelUpS2C_MsgID = 14351
)

var LegendLevelUpS2C_MsgID_name = map[int32]string{
	14351: "eMsgID",
}
var LegendLevelUpS2C_MsgID_value = map[string]int32{
	"eMsgID": 14351,
}

func (x LegendLevelUpS2C_MsgID) Enum() *LegendLevelUpS2C_MsgID {
	p := new(LegendLevelUpS2C_MsgID)
	*p = x
	return p
}
func (x LegendLevelUpS2C_MsgID) String() string {
	return proto.EnumName(LegendLevelUpS2C_MsgID_name, int32(x))
}
func (x *LegendLevelUpS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendLevelUpS2C_MsgID_value, data, "LegendLevelUpS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendLevelUpS2C_MsgID(value)
	return nil
}
func (LegendLevelUpS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{13, 0} }

type LegendStarUpC2S_MsgID int32

const (
	LegendStarUpC2S_eMsgID LegendStarUpC2S_MsgID = 14352
)

var LegendStarUpC2S_MsgID_name = map[int32]string{
	14352: "eMsgID",
}
var LegendStarUpC2S_MsgID_value = map[string]int32{
	"eMsgID": 14352,
}

func (x LegendStarUpC2S_MsgID) Enum() *LegendStarUpC2S_MsgID {
	p := new(LegendStarUpC2S_MsgID)
	*p = x
	return p
}
func (x LegendStarUpC2S_MsgID) String() string {
	return proto.EnumName(LegendStarUpC2S_MsgID_name, int32(x))
}
func (x *LegendStarUpC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendStarUpC2S_MsgID_value, data, "LegendStarUpC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendStarUpC2S_MsgID(value)
	return nil
}
func (LegendStarUpC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{14, 0} }

type LegendStarUpS2C_MsgID int32

const (
	LegendStarUpS2C_eMsgID LegendStarUpS2C_MsgID = 14352
)

var LegendStarUpS2C_MsgID_name = map[int32]string{
	14352: "eMsgID",
}
var LegendStarUpS2C_MsgID_value = map[string]int32{
	"eMsgID": 14352,
}

func (x LegendStarUpS2C_MsgID) Enum() *LegendStarUpS2C_MsgID {
	p := new(LegendStarUpS2C_MsgID)
	*p = x
	return p
}
func (x LegendStarUpS2C_MsgID) String() string {
	return proto.EnumName(LegendStarUpS2C_MsgID_name, int32(x))
}
func (x *LegendStarUpS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendStarUpS2C_MsgID_value, data, "LegendStarUpS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendStarUpS2C_MsgID(value)
	return nil
}
func (LegendStarUpS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor37, []int{15, 0} }

type LegendButtonStartC2S_MsgID int32

const (
	LegendButtonStartC2S_eMsgID LegendButtonStartC2S_MsgID = 14353
)

var LegendButtonStartC2S_MsgID_name = map[int32]string{
	14353: "eMsgID",
}
var LegendButtonStartC2S_MsgID_value = map[string]int32{
	"eMsgID": 14353,
}

func (x LegendButtonStartC2S_MsgID) Enum() *LegendButtonStartC2S_MsgID {
	p := new(LegendButtonStartC2S_MsgID)
	*p = x
	return p
}
func (x LegendButtonStartC2S_MsgID) String() string {
	return proto.EnumName(LegendButtonStartC2S_MsgID_name, int32(x))
}
func (x *LegendButtonStartC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendButtonStartC2S_MsgID_value, data, "LegendButtonStartC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendButtonStartC2S_MsgID(value)
	return nil
}
func (LegendButtonStartC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{16, 0}
}

type LegendButtonStartS2C_MsgID int32

const (
	LegendButtonStartS2C_eMsgID LegendButtonStartS2C_MsgID = 14353
)

var LegendButtonStartS2C_MsgID_name = map[int32]string{
	14353: "eMsgID",
}
var LegendButtonStartS2C_MsgID_value = map[string]int32{
	"eMsgID": 14353,
}

func (x LegendButtonStartS2C_MsgID) Enum() *LegendButtonStartS2C_MsgID {
	p := new(LegendButtonStartS2C_MsgID)
	*p = x
	return p
}
func (x LegendButtonStartS2C_MsgID) String() string {
	return proto.EnumName(LegendButtonStartS2C_MsgID_name, int32(x))
}
func (x *LegendButtonStartS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendButtonStartS2C_MsgID_value, data, "LegendButtonStartS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendButtonStartS2C_MsgID(value)
	return nil
}
func (LegendButtonStartS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{17, 0}
}

type LegendWearEquipC2S_MsgID int32

const (
	LegendWearEquipC2S_eMsgID LegendWearEquipC2S_MsgID = 14354
)

var LegendWearEquipC2S_MsgID_name = map[int32]string{
	14354: "eMsgID",
}
var LegendWearEquipC2S_MsgID_value = map[string]int32{
	"eMsgID": 14354,
}

func (x LegendWearEquipC2S_MsgID) Enum() *LegendWearEquipC2S_MsgID {
	p := new(LegendWearEquipC2S_MsgID)
	*p = x
	return p
}
func (x LegendWearEquipC2S_MsgID) String() string {
	return proto.EnumName(LegendWearEquipC2S_MsgID_name, int32(x))
}
func (x *LegendWearEquipC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendWearEquipC2S_MsgID_value, data, "LegendWearEquipC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendWearEquipC2S_MsgID(value)
	return nil
}
func (LegendWearEquipC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{18, 0}
}

type LegendWearEquipS2C_MsgID int32

const (
	LegendWearEquipS2C_eMsgID LegendWearEquipS2C_MsgID = 14354
)

var LegendWearEquipS2C_MsgID_name = map[int32]string{
	14354: "eMsgID",
}
var LegendWearEquipS2C_MsgID_value = map[string]int32{
	"eMsgID": 14354,
}

func (x LegendWearEquipS2C_MsgID) Enum() *LegendWearEquipS2C_MsgID {
	p := new(LegendWearEquipS2C_MsgID)
	*p = x
	return p
}
func (x LegendWearEquipS2C_MsgID) String() string {
	return proto.EnumName(LegendWearEquipS2C_MsgID_name, int32(x))
}
func (x *LegendWearEquipS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendWearEquipS2C_MsgID_value, data, "LegendWearEquipS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendWearEquipS2C_MsgID(value)
	return nil
}
func (LegendWearEquipS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{19, 0}
}

type StrengthLegendEquipC2S_MsgID int32

const (
	StrengthLegendEquipC2S_eMsgID StrengthLegendEquipC2S_MsgID = 14355
)

var StrengthLegendEquipC2S_MsgID_name = map[int32]string{
	14355: "eMsgID",
}
var StrengthLegendEquipC2S_MsgID_value = map[string]int32{
	"eMsgID": 14355,
}

func (x StrengthLegendEquipC2S_MsgID) Enum() *StrengthLegendEquipC2S_MsgID {
	p := new(StrengthLegendEquipC2S_MsgID)
	*p = x
	return p
}
func (x StrengthLegendEquipC2S_MsgID) String() string {
	return proto.EnumName(StrengthLegendEquipC2S_MsgID_name, int32(x))
}
func (x *StrengthLegendEquipC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StrengthLegendEquipC2S_MsgID_value, data, "StrengthLegendEquipC2S_MsgID")
	if err != nil {
		return err
	}
	*x = StrengthLegendEquipC2S_MsgID(value)
	return nil
}
func (StrengthLegendEquipC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{20, 0}
}

type StrengthLegendEquipS2C_MsgID int32

const (
	StrengthLegendEquipS2C_eMsgID StrengthLegendEquipS2C_MsgID = 14355
)

var StrengthLegendEquipS2C_MsgID_name = map[int32]string{
	14355: "eMsgID",
}
var StrengthLegendEquipS2C_MsgID_value = map[string]int32{
	"eMsgID": 14355,
}

func (x StrengthLegendEquipS2C_MsgID) Enum() *StrengthLegendEquipS2C_MsgID {
	p := new(StrengthLegendEquipS2C_MsgID)
	*p = x
	return p
}
func (x StrengthLegendEquipS2C_MsgID) String() string {
	return proto.EnumName(StrengthLegendEquipS2C_MsgID_name, int32(x))
}
func (x *StrengthLegendEquipS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StrengthLegendEquipS2C_MsgID_value, data, "StrengthLegendEquipS2C_MsgID")
	if err != nil {
		return err
	}
	*x = StrengthLegendEquipS2C_MsgID(value)
	return nil
}
func (StrengthLegendEquipS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{21, 0}
}

type LegendWearAllEquipC2S_MsgID int32

const (
	LegendWearAllEquipC2S_eMsgID LegendWearAllEquipC2S_MsgID = 14356
)

var LegendWearAllEquipC2S_MsgID_name = map[int32]string{
	14356: "eMsgID",
}
var LegendWearAllEquipC2S_MsgID_value = map[string]int32{
	"eMsgID": 14356,
}

func (x LegendWearAllEquipC2S_MsgID) Enum() *LegendWearAllEquipC2S_MsgID {
	p := new(LegendWearAllEquipC2S_MsgID)
	*p = x
	return p
}
func (x LegendWearAllEquipC2S_MsgID) String() string {
	return proto.EnumName(LegendWearAllEquipC2S_MsgID_name, int32(x))
}
func (x *LegendWearAllEquipC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendWearAllEquipC2S_MsgID_value, data, "LegendWearAllEquipC2S_MsgID")
	if err != nil {
		return err
	}
	*x = LegendWearAllEquipC2S_MsgID(value)
	return nil
}
func (LegendWearAllEquipC2S_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{22, 0}
}

type LegendWearAllEquipS2C_MsgID int32

const (
	LegendWearAllEquipS2C_eMsgID LegendWearAllEquipS2C_MsgID = 14356
)

var LegendWearAllEquipS2C_MsgID_name = map[int32]string{
	14356: "eMsgID",
}
var LegendWearAllEquipS2C_MsgID_value = map[string]int32{
	"eMsgID": 14356,
}

func (x LegendWearAllEquipS2C_MsgID) Enum() *LegendWearAllEquipS2C_MsgID {
	p := new(LegendWearAllEquipS2C_MsgID)
	*p = x
	return p
}
func (x LegendWearAllEquipS2C_MsgID) String() string {
	return proto.EnumName(LegendWearAllEquipS2C_MsgID_name, int32(x))
}
func (x *LegendWearAllEquipS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LegendWearAllEquipS2C_MsgID_value, data, "LegendWearAllEquipS2C_MsgID")
	if err != nil {
		return err
	}
	*x = LegendWearAllEquipS2C_MsgID(value)
	return nil
}
func (LegendWearAllEquipS2C_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor37, []int{23, 0}
}

// 名宿
type LegendData struct {
	// id
	Id *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// 位置（0:无位置 1:出场位 2-6:协助位）
	Field *int32 `protobuf:"varint,2,opt,name=field" json:"field,omitempty"`
	// 等级
	Level *int32 `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	// 星级
	Star *int32 `protobuf:"varint,4,opt,name=star" json:"star,omitempty"`
	// 等级属性培养
	Cultivates []int32 `protobuf:"varint,5,rep,name=cultivates" json:"cultivates,omitempty"`
	// 等级培养消耗数量
	ConsumeNum *int32 `protobuf:"varint,6,opt,name=consumeNum" json:"consumeNum,omitempty"`
	// 装备
	Equipments       []int64 `protobuf:"varint,7,rep,name=equipments" json:"equipments,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LegendData) Reset()                    { *m = LegendData{} }
func (m *LegendData) String() string            { return proto.CompactTextString(m) }
func (*LegendData) ProtoMessage()               {}
func (*LegendData) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{0} }

func (m *LegendData) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *LegendData) GetField() int32 {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return 0
}

func (m *LegendData) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *LegendData) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

func (m *LegendData) GetCultivates() []int32 {
	if m != nil {
		return m.Cultivates
	}
	return nil
}

func (m *LegendData) GetConsumeNum() int32 {
	if m != nil && m.ConsumeNum != nil {
		return *m.ConsumeNum
	}
	return 0
}

func (m *LegendData) GetEquipments() []int64 {
	if m != nil {
		return m.Equipments
	}
	return nil
}

// 名宿开放栏位
type LegendFieldData struct {
	// 开放名宿栏位
	Fields           []int32 `protobuf:"varint,1,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LegendFieldData) Reset()                    { *m = LegendFieldData{} }
func (m *LegendFieldData) String() string            { return proto.CompactTextString(m) }
func (*LegendFieldData) ProtoMessage()               {}
func (*LegendFieldData) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{1} }

func (m *LegendFieldData) GetFields() []int32 {
	if m != nil {
		return m.Fields
	}
	return nil
}

// 客户端无数据时请求数据（功能开放的前提下）
type LegendGetDataC2S struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendGetDataC2S) Reset()                    { *m = LegendGetDataC2S{} }
func (m *LegendGetDataC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendGetDataC2S) ProtoMessage()               {}
func (*LegendGetDataC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{2} }

// 上线同步名宿s2c
type LegendGetDataS2C struct {
	// 名宿
	Legends []*LegendData `protobuf:"bytes,1,rep,name=legends" json:"legends,omitempty"`
	// 开放的栏位
	Fields           []int32 `protobuf:"varint,2,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LegendGetDataS2C) Reset()                    { *m = LegendGetDataS2C{} }
func (m *LegendGetDataS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendGetDataS2C) ProtoMessage()               {}
func (*LegendGetDataS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{3} }

func (m *LegendGetDataS2C) GetLegends() []*LegendData {
	if m != nil {
		return m.Legends
	}
	return nil
}

func (m *LegendGetDataS2C) GetFields() []int32 {
	if m != nil {
		return m.Fields
	}
	return nil
}

// 名宿解锁c2s
type LegendUnlockC2S struct {
	// 名宿id
	LegendId         *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendUnlockC2S) Reset()                    { *m = LegendUnlockC2S{} }
func (m *LegendUnlockC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendUnlockC2S) ProtoMessage()               {}
func (*LegendUnlockC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{4} }

func (m *LegendUnlockC2S) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

// 名宿解锁s2c
type LegendUnlockS2C struct {
	// 名宿
	Legend           *LegendData `protobuf:"bytes,1,opt,name=legend" json:"legend,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *LegendUnlockS2C) Reset()                    { *m = LegendUnlockS2C{} }
func (m *LegendUnlockS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendUnlockS2C) ProtoMessage()               {}
func (*LegendUnlockS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{5} }

func (m *LegendUnlockS2C) GetLegend() *LegendData {
	if m != nil {
		return m.Legend
	}
	return nil
}

// 名宿出场位解锁s2c
type LegendUnlockFieldS2C struct {
	// 解锁栏位（1:出场位 2-6:协助位
	Field            []int32 `protobuf:"varint,1,rep,name=field" json:"field,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LegendUnlockFieldS2C) Reset()                    { *m = LegendUnlockFieldS2C{} }
func (m *LegendUnlockFieldS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendUnlockFieldS2C) ProtoMessage()               {}
func (*LegendUnlockFieldS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{6} }

func (m *LegendUnlockFieldS2C) GetField() []int32 {
	if m != nil {
		return m.Field
	}
	return nil
}

type LegendPlayField struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 栏位
	Field            *int32 `protobuf:"varint,2,opt,name=field" json:"field,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendPlayField) Reset()                    { *m = LegendPlayField{} }
func (m *LegendPlayField) String() string            { return proto.CompactTextString(m) }
func (*LegendPlayField) ProtoMessage()               {}
func (*LegendPlayField) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{7} }

func (m *LegendPlayField) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendPlayField) GetField() int32 {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return 0
}

// 名宿上场操作c2s
// 如果栏位上无名宿：新名宿新位置
// 如果栏位上有名宿：交换两个名宿位置
type LegendPlayC2S struct {
	LegendField      *LegendPlayField `protobuf:"bytes,1,opt,name=legendField" json:"legendField,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *LegendPlayC2S) Reset()                    { *m = LegendPlayC2S{} }
func (m *LegendPlayC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendPlayC2S) ProtoMessage()               {}
func (*LegendPlayC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{8} }

func (m *LegendPlayC2S) GetLegendField() *LegendPlayField {
	if m != nil {
		return m.LegendField
	}
	return nil
}

// 名宿上场操作s2c
type LegendPlayS2C struct {
	// 上场或交换后的名宿新位置
	Legends          []*LegendData `protobuf:"bytes,1,rep,name=legends" json:"legends,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *LegendPlayS2C) Reset()                    { *m = LegendPlayS2C{} }
func (m *LegendPlayS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendPlayS2C) ProtoMessage()               {}
func (*LegendPlayS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{9} }

func (m *LegendPlayS2C) GetLegends() []*LegendData {
	if m != nil {
		return m.Legends
	}
	return nil
}

// 名宿等级培养c2s
type LegendLevelCultivateC2S struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 培养次数
	CultivateNum     *int32 `protobuf:"varint,2,opt,name=cultivateNum" json:"cultivateNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendLevelCultivateC2S) Reset()                    { *m = LegendLevelCultivateC2S{} }
func (m *LegendLevelCultivateC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendLevelCultivateC2S) ProtoMessage()               {}
func (*LegendLevelCultivateC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{10} }

func (m *LegendLevelCultivateC2S) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendLevelCultivateC2S) GetCultivateNum() int32 {
	if m != nil && m.CultivateNum != nil {
		return *m.CultivateNum
	}
	return 0
}

// 名宿等级培养s2c
type LegendLevelCultivateS2C struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 属性培养
	Cultivates []int32 `protobuf:"varint,2,rep,name=cultivates" json:"cultivates,omitempty"`
	// 已培养的总次数
	CultivateNum     *int32 `protobuf:"varint,3,opt,name=cultivateNum" json:"cultivateNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendLevelCultivateS2C) Reset()                    { *m = LegendLevelCultivateS2C{} }
func (m *LegendLevelCultivateS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendLevelCultivateS2C) ProtoMessage()               {}
func (*LegendLevelCultivateS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{11} }

func (m *LegendLevelCultivateS2C) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendLevelCultivateS2C) GetCultivates() []int32 {
	if m != nil {
		return m.Cultivates
	}
	return nil
}

func (m *LegendLevelCultivateS2C) GetCultivateNum() int32 {
	if m != nil && m.CultivateNum != nil {
		return *m.CultivateNum
	}
	return 0
}

// 名宿升级c2s
type LegendLevelUpC2S struct {
	// 名宿id
	LegendId         *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendLevelUpC2S) Reset()                    { *m = LegendLevelUpC2S{} }
func (m *LegendLevelUpC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendLevelUpC2S) ProtoMessage()               {}
func (*LegendLevelUpC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{12} }

func (m *LegendLevelUpC2S) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

// 名宿升级s2c
type LegendLevelUpS2C struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// level
	Level            *int32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendLevelUpS2C) Reset()                    { *m = LegendLevelUpS2C{} }
func (m *LegendLevelUpS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendLevelUpS2C) ProtoMessage()               {}
func (*LegendLevelUpS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{13} }

func (m *LegendLevelUpS2C) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendLevelUpS2C) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

// 名宿升星c2s
type LegendStarUpC2S struct {
	// 名宿id
	LegendId         *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendStarUpC2S) Reset()                    { *m = LegendStarUpC2S{} }
func (m *LegendStarUpC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendStarUpC2S) ProtoMessage()               {}
func (*LegendStarUpC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{14} }

func (m *LegendStarUpC2S) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

// 名宿升星s2c
type LegendStarUpS2C struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// star
	Star             *int32 `protobuf:"varint,2,opt,name=star" json:"star,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendStarUpS2C) Reset()                    { *m = LegendStarUpS2C{} }
func (m *LegendStarUpS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendStarUpS2C) ProtoMessage()               {}
func (*LegendStarUpS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{15} }

func (m *LegendStarUpS2C) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendStarUpS2C) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

// 名宿一键上阵c2s
type LegendButtonStartC2S struct {
	LegendFields     []*LegendPlayField `protobuf:"bytes,1,rep,name=legendFields" json:"legendFields,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *LegendButtonStartC2S) Reset()                    { *m = LegendButtonStartC2S{} }
func (m *LegendButtonStartC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendButtonStartC2S) ProtoMessage()               {}
func (*LegendButtonStartC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{16} }

func (m *LegendButtonStartC2S) GetLegendFields() []*LegendPlayField {
	if m != nil {
		return m.LegendFields
	}
	return nil
}

// 名宿一键上阵s2c
type LegendButtonStartS2C struct {
	// 名宿
	Legends          []*LegendData `protobuf:"bytes,1,rep,name=legends" json:"legends,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *LegendButtonStartS2C) Reset()                    { *m = LegendButtonStartS2C{} }
func (m *LegendButtonStartS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendButtonStartS2C) ProtoMessage()               {}
func (*LegendButtonStartS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{17} }

func (m *LegendButtonStartS2C) GetLegends() []*LegendData {
	if m != nil {
		return m.Legends
	}
	return nil
}

// 名宿穿,脱装备c2s
type LegendWearEquipC2S struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 位置 1~4(用装备配置表的part字段 11~14)
	Part *int32 `protobuf:"varint,2,opt,name=part" json:"part,omitempty"`
	// 装备ID 装备ID=0时 脱下这个部位的装备
	InstId           *int64 `protobuf:"varint,3,opt,name=instId" json:"instId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendWearEquipC2S) Reset()                    { *m = LegendWearEquipC2S{} }
func (m *LegendWearEquipC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendWearEquipC2S) ProtoMessage()               {}
func (*LegendWearEquipC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{18} }

func (m *LegendWearEquipC2S) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendWearEquipC2S) GetPart() int32 {
	if m != nil && m.Part != nil {
		return *m.Part
	}
	return 0
}

func (m *LegendWearEquipC2S) GetInstId() int64 {
	if m != nil && m.InstId != nil {
		return *m.InstId
	}
	return 0
}

// 返回名宿穿,脱装备s2c
type LegendWearEquipS2C struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 位置 1~4(用装备配置表的part字段 11~14)
	Part *int32 `protobuf:"varint,2,opt,name=part" json:"part,omitempty"`
	// 装备ID 装备ID=0时 脱下这个部位的装备
	InstId           *int64 `protobuf:"varint,3,opt,name=instId" json:"instId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendWearEquipS2C) Reset()                    { *m = LegendWearEquipS2C{} }
func (m *LegendWearEquipS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendWearEquipS2C) ProtoMessage()               {}
func (*LegendWearEquipS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{19} }

func (m *LegendWearEquipS2C) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendWearEquipS2C) GetPart() int32 {
	if m != nil && m.Part != nil {
		return *m.Part
	}
	return 0
}

func (m *LegendWearEquipS2C) GetInstId() int64 {
	if m != nil && m.InstId != nil {
		return *m.InstId
	}
	return 0
}

// 名宿装备强化c2s
type StrengthLegendEquipC2S struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 装备ID
	InstId *int64 `protobuf:"varint,2,opt,name=instId" json:"instId,omitempty"`
	// 强化类型 0强化一次 1一键强化
	Type             *int32 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StrengthLegendEquipC2S) Reset()                    { *m = StrengthLegendEquipC2S{} }
func (m *StrengthLegendEquipC2S) String() string            { return proto.CompactTextString(m) }
func (*StrengthLegendEquipC2S) ProtoMessage()               {}
func (*StrengthLegendEquipC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{20} }

func (m *StrengthLegendEquipC2S) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *StrengthLegendEquipC2S) GetInstId() int64 {
	if m != nil && m.InstId != nil {
		return *m.InstId
	}
	return 0
}

func (m *StrengthLegendEquipC2S) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 返回名宿装备强化s2c
type StrengthLegendEquipS2C struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 装备ID
	InstId *int64 `protobuf:"varint,2,opt,name=instId" json:"instId,omitempty"`
	// 强化后装备等级
	Level            *int32 `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StrengthLegendEquipS2C) Reset()                    { *m = StrengthLegendEquipS2C{} }
func (m *StrengthLegendEquipS2C) String() string            { return proto.CompactTextString(m) }
func (*StrengthLegendEquipS2C) ProtoMessage()               {}
func (*StrengthLegendEquipS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{21} }

func (m *StrengthLegendEquipS2C) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *StrengthLegendEquipS2C) GetInstId() int64 {
	if m != nil && m.InstId != nil {
		return *m.InstId
	}
	return 0
}

func (m *StrengthLegendEquipS2C) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

// 名宿一键装备c2s
type LegendWearAllEquipC2S struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 类型0穿装备 1脱装备
	Type             *int32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LegendWearAllEquipC2S) Reset()                    { *m = LegendWearAllEquipC2S{} }
func (m *LegendWearAllEquipC2S) String() string            { return proto.CompactTextString(m) }
func (*LegendWearAllEquipC2S) ProtoMessage()               {}
func (*LegendWearAllEquipC2S) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{22} }

func (m *LegendWearAllEquipC2S) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendWearAllEquipC2S) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 返回名宿 一键装备s2c
type LegendWearAllEquipS2C struct {
	// 名宿id
	LegendId *int32 `protobuf:"varint,1,opt,name=legendId" json:"legendId,omitempty"`
	// 类型0穿装备 1脱装备
	Type *int32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	// 穿上的装备IDs
	Equipments       []int64 `protobuf:"varint,3,rep,name=equipments" json:"equipments,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LegendWearAllEquipS2C) Reset()                    { *m = LegendWearAllEquipS2C{} }
func (m *LegendWearAllEquipS2C) String() string            { return proto.CompactTextString(m) }
func (*LegendWearAllEquipS2C) ProtoMessage()               {}
func (*LegendWearAllEquipS2C) Descriptor() ([]byte, []int) { return fileDescriptor37, []int{23} }

func (m *LegendWearAllEquipS2C) GetLegendId() int32 {
	if m != nil && m.LegendId != nil {
		return *m.LegendId
	}
	return 0
}

func (m *LegendWearAllEquipS2C) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *LegendWearAllEquipS2C) GetEquipments() []int64 {
	if m != nil {
		return m.Equipments
	}
	return nil
}

func init() {
	proto.RegisterType((*LegendData)(nil), "legendData")
	proto.RegisterType((*LegendFieldData)(nil), "legendFieldData")
	proto.RegisterType((*LegendGetDataC2S)(nil), "legendGetDataC2S")
	proto.RegisterType((*LegendGetDataS2C)(nil), "legendGetDataS2C")
	proto.RegisterType((*LegendUnlockC2S)(nil), "legendUnlockC2S")
	proto.RegisterType((*LegendUnlockS2C)(nil), "legendUnlockS2C")
	proto.RegisterType((*LegendUnlockFieldS2C)(nil), "legendUnlockFieldS2C")
	proto.RegisterType((*LegendPlayField)(nil), "legendPlayField")
	proto.RegisterType((*LegendPlayC2S)(nil), "legendPlayC2S")
	proto.RegisterType((*LegendPlayS2C)(nil), "legendPlayS2C")
	proto.RegisterType((*LegendLevelCultivateC2S)(nil), "legendLevelCultivateC2S")
	proto.RegisterType((*LegendLevelCultivateS2C)(nil), "legendLevelCultivateS2C")
	proto.RegisterType((*LegendLevelUpC2S)(nil), "legendLevelUpC2S")
	proto.RegisterType((*LegendLevelUpS2C)(nil), "legendLevelUpS2C")
	proto.RegisterType((*LegendStarUpC2S)(nil), "legendStarUpC2S")
	proto.RegisterType((*LegendStarUpS2C)(nil), "legendStarUpS2C")
	proto.RegisterType((*LegendButtonStartC2S)(nil), "legendButtonStartC2S")
	proto.RegisterType((*LegendButtonStartS2C)(nil), "legendButtonStartS2C")
	proto.RegisterType((*LegendWearEquipC2S)(nil), "LegendWearEquipC2S")
	proto.RegisterType((*LegendWearEquipS2C)(nil), "LegendWearEquipS2C")
	proto.RegisterType((*StrengthLegendEquipC2S)(nil), "StrengthLegendEquipC2S")
	proto.RegisterType((*StrengthLegendEquipS2C)(nil), "StrengthLegendEquipS2C")
	proto.RegisterType((*LegendWearAllEquipC2S)(nil), "LegendWearAllEquipC2S")
	proto.RegisterType((*LegendWearAllEquipS2C)(nil), "LegendWearAllEquipS2C")
	proto.RegisterEnum("LegendGetDataC2S_MsgID", LegendGetDataC2S_MsgID_name, LegendGetDataC2S_MsgID_value)
	proto.RegisterEnum("LegendGetDataS2C_MsgID", LegendGetDataS2C_MsgID_name, LegendGetDataS2C_MsgID_value)
	proto.RegisterEnum("LegendUnlockC2S_MsgID", LegendUnlockC2S_MsgID_name, LegendUnlockC2S_MsgID_value)
	proto.RegisterEnum("LegendUnlockS2C_MsgID", LegendUnlockS2C_MsgID_name, LegendUnlockS2C_MsgID_value)
	proto.RegisterEnum("LegendUnlockFieldS2C_MsgID", LegendUnlockFieldS2C_MsgID_name, LegendUnlockFieldS2C_MsgID_value)
	proto.RegisterEnum("LegendPlayC2S_MsgID", LegendPlayC2S_MsgID_name, LegendPlayC2S_MsgID_value)
	proto.RegisterEnum("LegendPlayS2C_MsgID", LegendPlayS2C_MsgID_name, LegendPlayS2C_MsgID_value)
	proto.RegisterEnum("LegendLevelCultivateC2S_MsgID", LegendLevelCultivateC2S_MsgID_name, LegendLevelCultivateC2S_MsgID_value)
	proto.RegisterEnum("LegendLevelCultivateS2C_MsgID", LegendLevelCultivateS2C_MsgID_name, LegendLevelCultivateS2C_MsgID_value)
	proto.RegisterEnum("LegendLevelUpC2S_MsgID", LegendLevelUpC2S_MsgID_name, LegendLevelUpC2S_MsgID_value)
	proto.RegisterEnum("LegendLevelUpS2C_MsgID", LegendLevelUpS2C_MsgID_name, LegendLevelUpS2C_MsgID_value)
	proto.RegisterEnum("LegendStarUpC2S_MsgID", LegendStarUpC2S_MsgID_name, LegendStarUpC2S_MsgID_value)
	proto.RegisterEnum("LegendStarUpS2C_MsgID", LegendStarUpS2C_MsgID_name, LegendStarUpS2C_MsgID_value)
	proto.RegisterEnum("LegendButtonStartC2S_MsgID", LegendButtonStartC2S_MsgID_name, LegendButtonStartC2S_MsgID_value)
	proto.RegisterEnum("LegendButtonStartS2C_MsgID", LegendButtonStartS2C_MsgID_name, LegendButtonStartS2C_MsgID_value)
	proto.RegisterEnum("LegendWearEquipC2S_MsgID", LegendWearEquipC2S_MsgID_name, LegendWearEquipC2S_MsgID_value)
	proto.RegisterEnum("LegendWearEquipS2C_MsgID", LegendWearEquipS2C_MsgID_name, LegendWearEquipS2C_MsgID_value)
	proto.RegisterEnum("StrengthLegendEquipC2S_MsgID", StrengthLegendEquipC2S_MsgID_name, StrengthLegendEquipC2S_MsgID_value)
	proto.RegisterEnum("StrengthLegendEquipS2C_MsgID", StrengthLegendEquipS2C_MsgID_name, StrengthLegendEquipS2C_MsgID_value)
	proto.RegisterEnum("LegendWearAllEquipC2S_MsgID", LegendWearAllEquipC2S_MsgID_name, LegendWearAllEquipC2S_MsgID_value)
	proto.RegisterEnum("LegendWearAllEquipS2C_MsgID", LegendWearAllEquipS2C_MsgID_name, LegendWearAllEquipS2C_MsgID_value)
}

func init() { proto.RegisterFile("legend.proto", fileDescriptor37) }

var fileDescriptor37 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x95, 0xcd, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xd5, 0x64, 0xed, 0xd0, 0xdb, 0x0e, 0xaa, 0xa8, 0x40, 0x24, 0x38, 0x0c, 0x4b, 0xa0,
	0x9d, 0x7a, 0xe8, 0x0d, 0x38, 0x41, 0xcb, 0xa6, 0xa2, 0x0e, 0x21, 0x95, 0x31, 0x89, 0x03, 0x28,
	0x5a, 0x4d, 0x89, 0xe6, 0x26, 0xa6, 0x71, 0x26, 0xed, 0xc6, 0x99, 0xef, 0xaf, 0x3f, 0x18, 0x7f,
	0xc4, 0xf9, 0xaa, 0x1d, 0xb6, 0xdd, 0x1a, 0xf7, 0x7d, 0x7f, 0xcf, 0x13, 0xfb, 0xc9, 0x6b, 0xe8,
	0x11, 0xbc, 0xc4, 0xd1, 0x62, 0x48, 0xd7, 0x31, 0x8b, 0xd1, 0xa7, 0x16, 0x80, 0x5a, 0x98, 0x04,
	0x2c, 0xf0, 0x00, 0x9c, 0x70, 0xe1, 0xb7, 0x76, 0x5b, 0x7b, 0x6d, 0x6f, 0x07, 0xda, 0xef, 0x43,
	0x4c, 0x16, 0xbe, 0xa3, 0x1f, 0x09, 0x3e, 0xc3, 0xc4, 0x77, 0xe5, 0x63, 0x0f, 0xb6, 0x12, 0x16,
	0xac, 0xfd, 0x2d, 0xf9, 0xc4, 0x1b, 0x4f, 0x52, 0xc2, 0xc2, 0xb3, 0x80, 0xe1, 0xc4, 0x6f, 0xef,
	0xba, 0xd9, 0x5a, 0x1c, 0x25, 0xe9, 0x0a, 0xbf, 0x48, 0x57, 0x7e, 0x47, 0xd7, 0xe1, 0x8f, 0x69,
	0x48, 0x57, 0x38, 0x62, 0x89, 0xbf, 0xcd, 0xeb, 0x5c, 0x74, 0x0f, 0x6e, 0x28, 0x07, 0xfb, 0x42,
	0x4d, 0xda, 0xb8, 0x0e, 0x1d, 0x29, 0x9d, 0x70, 0x2b, 0x1c, 0x85, 0xf6, 0xa0, 0xaf, 0x4a, 0x0e,
	0x30, 0x13, 0x05, 0xe3, 0xd1, 0x1c, 0x0d, 0xa0, 0x7d, 0x98, 0x2c, 0xa7, 0x13, 0xaf, 0x0b, 0x1d,
	0x2c, 0x7f, 0xf5, 0x3f, 0x53, 0xf4, 0xba, 0x56, 0x39, 0x1f, 0x8d, 0xbd, 0xbb, 0xb0, 0xad, 0xd6,
	0x14, 0xae, 0x3b, 0xea, 0x0e, 0x4b, 0xaf, 0x5c, 0x68, 0x39, 0x52, 0xcb, 0xcc, 0x7d, 0xa8, 0x4d,
	0x1e, 0x45, 0x24, 0x3e, 0x39, 0xe5, 0x06, 0xbc, 0x3e, 0x5c, 0x53, 0x4b, 0xd3, 0x6c, 0xc7, 0x4c,
	0xad, 0x5f, 0x28, 0x9a, 0x54, 0x5b, 0x85, 0xa3, 0x3b, 0xd0, 0x51, 0x4b, 0xb2, 0xb1, 0x6a, 0xc8,
	0x42, 0x79, 0x0c, 0x83, 0x32, 0x45, 0xee, 0x95, 0x40, 0xe5, 0xa7, 0xd4, 0xb2, 0xb9, 0xff, 0x4a,
	0xd1, 0x48, 0x5b, 0x78, 0x49, 0x82, 0x73, 0xd9, 0xba, 0xe9, 0xbe, 0x76, 0xde, 0x68, 0x06, 0x3b,
	0x45, 0x8f, 0x78, 0xdf, 0xfb, 0xd0, 0x2d, 0x9d, 0x53, 0xe6, 0xbc, 0x3f, 0xac, 0x81, 0x4d, 0x0e,
	0xbe, 0x51, 0x34, 0x2e, 0xd3, 0xfe, 0x7b, 0x28, 0x16, 0xc8, 0x31, 0xdc, 0x56, 0x35, 0x33, 0x11,
	0xc4, 0xb1, 0x0e, 0x9c, 0xf1, 0x30, 0xbc, 0x01, 0xf4, 0xf2, 0x48, 0x8a, 0x00, 0x3a, 0xb6, 0x23,
	0xfa, 0x4e, 0xd1, 0xa9, 0x19, 0x2c, 0x7c, 0x6e, 0x82, 0xab, 0x59, 0x97, 0xa1, 0xd9, 0x10, 0x73,
	0x1b, 0xc4, 0x1e, 0xe9, 0x88, 0x4a, 0xb1, 0x23, 0x7a, 0xe1, 0x2c, 0xfd, 0xa0, 0x68, 0x5a, 0xeb,
	0x35, 0x3b, 0xcc, 0x3f, 0x55, 0xa7, 0x01, 0x95, 0x27, 0x7a, 0xce, 0x3f, 0xe3, 0x4b, 0xb8, 0xf8,
	0x49, 0xd1, 0x41, 0xb5, 0xd5, 0x6c, 0x42, 0x0f, 0x08, 0xa7, 0x01, 0xf4, 0x4a, 0x87, 0xfa, 0x69,
	0xca, 0x58, 0x1c, 0x09, 0x1c, 0x13, 0x46, 0x1e, 0xe8, 0x29, 0xb5, 0x5f, 0x4c, 0x81, 0x0b, 0x66,
	0xed, 0x17, 0x45, 0xcf, 0x0d, 0xd4, 0x2b, 0x45, 0x8e, 0xb3, 0xde, 0x80, 0x37, 0x93, 0x35, 0xc7,
	0x38, 0x58, 0x3f, 0x13, 0xa3, 0xcb, 0x9c, 0x36, 0xfe, 0xb6, 0x94, 0xcb, 0x64, 0xb3, 0x92, 0xcf,
	0x94, 0x30, 0x4a, 0x18, 0xff, 0x57, 0x04, 0xc1, 0x35, 0xb1, 0x7f, 0x9b, 0xd8, 0xd6, 0x9d, 0xbc,
	0x34, 0xfb, 0x2d, 0xdc, 0x9a, 0xb3, 0x35, 0x8e, 0x96, 0xec, 0x83, 0xd2, 0x68, 0xf0, 0x5e, 0x10,
	0x85, 0x82, 0x2b, 0xf4, 0xd8, 0x39, 0xc5, 0xf6, 0x10, 0xff, 0xa1, 0xe8, 0x9d, 0x91, 0x6f, 0xf6,
	0x5f, 0xe7, 0x57, 0x6f, 0x12, 0x8b, 0xc0, 0x21, 0xdc, 0x2c, 0x36, 0xe7, 0x09, 0x21, 0xcd, 0x7b,
	0x2f, 0xfd, 0x5a, 0x93, 0xf6, 0x97, 0xa2, 0xc0, 0x84, 0xb3, 0x6e, 0x77, 0x81, 0xab, 0xdd, 0x58,
	0xae, 0xbc, 0xb1, 0x8c, 0x12, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x44, 0xa5, 0xa1, 0x59,
	0x07, 0x00, 0x00,
}
