// Code generated by protoc-gen-go.
// source: salary.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BuySalaryC2S_MsgID int32

const (
	BuySalaryC2S_eMsgID BuySalaryC2S_MsgID = 15361
)

var BuySalaryC2S_MsgID_name = map[int32]string{
	15361: "eMsgID",
}
var BuySalaryC2S_MsgID_value = map[string]int32{
	"eMsgID": 15361,
}

func (x BuySalaryC2S_MsgID) Enum() *BuySalaryC2S_MsgID {
	p := new(BuySalaryC2S_MsgID)
	*p = x
	return p
}
func (x BuySalaryC2S_MsgID) String() string {
	return proto.EnumName(BuySalaryC2S_MsgID_name, int32(x))
}
func (x *BuySalaryC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BuySalaryC2S_MsgID_value, data, "BuySalaryC2S_MsgID")
	if err != nil {
		return err
	}
	*x = BuySalaryC2S_MsgID(value)
	return nil
}
func (BuySalaryC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor65, []int{1, 0} }

type BuySalaryS2C_MsgID int32

const (
	BuySalaryS2C_eMsgID BuySalaryS2C_MsgID = 15361
)

var BuySalaryS2C_MsgID_name = map[int32]string{
	15361: "eMsgID",
}
var BuySalaryS2C_MsgID_value = map[string]int32{
	"eMsgID": 15361,
}

func (x BuySalaryS2C_MsgID) Enum() *BuySalaryS2C_MsgID {
	p := new(BuySalaryS2C_MsgID)
	*p = x
	return p
}
func (x BuySalaryS2C_MsgID) String() string {
	return proto.EnumName(BuySalaryS2C_MsgID_name, int32(x))
}
func (x *BuySalaryS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BuySalaryS2C_MsgID_value, data, "BuySalaryS2C_MsgID")
	if err != nil {
		return err
	}
	*x = BuySalaryS2C_MsgID(value)
	return nil
}
func (BuySalaryS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor65, []int{2, 0} }

type SalaryDataS2C_MsgID int32

const (
	SalaryDataS2C_eMsgID SalaryDataS2C_MsgID = 15362
)

var SalaryDataS2C_MsgID_name = map[int32]string{
	15362: "eMsgID",
}
var SalaryDataS2C_MsgID_value = map[string]int32{
	"eMsgID": 15362,
}

func (x SalaryDataS2C_MsgID) Enum() *SalaryDataS2C_MsgID {
	p := new(SalaryDataS2C_MsgID)
	*p = x
	return p
}
func (x SalaryDataS2C_MsgID) String() string {
	return proto.EnumName(SalaryDataS2C_MsgID_name, int32(x))
}
func (x *SalaryDataS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SalaryDataS2C_MsgID_value, data, "SalaryDataS2C_MsgID")
	if err != nil {
		return err
	}
	*x = SalaryDataS2C_MsgID(value)
	return nil
}
func (SalaryDataS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor65, []int{3, 0} }

// 工资帽
type Salary struct {
	BuySalaryCfgId   *int32 `protobuf:"varint,1,opt,name=buySalaryCfgId" json:"buySalaryCfgId,omitempty"`
	MonthCardId      *int32 `protobuf:"varint,2,opt,name=monthCardId" json:"monthCardId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Salary) Reset()                    { *m = Salary{} }
func (m *Salary) String() string            { return proto.CompactTextString(m) }
func (*Salary) ProtoMessage()               {}
func (*Salary) Descriptor() ([]byte, []int) { return fileDescriptor65, []int{0} }

func (m *Salary) GetBuySalaryCfgId() int32 {
	if m != nil && m.BuySalaryCfgId != nil {
		return *m.BuySalaryCfgId
	}
	return 0
}

func (m *Salary) GetMonthCardId() int32 {
	if m != nil && m.MonthCardId != nil {
		return *m.MonthCardId
	}
	return 0
}

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
// 工资帽购买
type BuySalaryC2S struct {
	SalaryCfgId      *int32 `protobuf:"varint,1,opt,name=salaryCfgId" json:"salaryCfgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BuySalaryC2S) Reset()                    { *m = BuySalaryC2S{} }
func (m *BuySalaryC2S) String() string            { return proto.CompactTextString(m) }
func (*BuySalaryC2S) ProtoMessage()               {}
func (*BuySalaryC2S) Descriptor() ([]byte, []int) { return fileDescriptor65, []int{1} }

func (m *BuySalaryC2S) GetSalaryCfgId() int32 {
	if m != nil && m.SalaryCfgId != nil {
		return *m.SalaryCfgId
	}
	return 0
}

// 返回 购买
type BuySalaryS2C struct {
	SalaryCfgId      *int32 `protobuf:"varint,1,opt,name=salaryCfgId" json:"salaryCfgId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BuySalaryS2C) Reset()                    { *m = BuySalaryS2C{} }
func (m *BuySalaryS2C) String() string            { return proto.CompactTextString(m) }
func (*BuySalaryS2C) ProtoMessage()               {}
func (*BuySalaryS2C) Descriptor() ([]byte, []int) { return fileDescriptor65, []int{2} }

func (m *BuySalaryS2C) GetSalaryCfgId() int32 {
	if m != nil && m.SalaryCfgId != nil {
		return *m.SalaryCfgId
	}
	return 0
}

// 返回工资帽信息
type SalaryDataS2C struct {
	BuySalaryCfgId   *int32 `protobuf:"varint,1,opt,name=buySalaryCfgId" json:"buySalaryCfgId,omitempty"`
	MonthCardId      *int32 `protobuf:"varint,2,opt,name=monthCardId" json:"monthCardId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SalaryDataS2C) Reset()                    { *m = SalaryDataS2C{} }
func (m *SalaryDataS2C) String() string            { return proto.CompactTextString(m) }
func (*SalaryDataS2C) ProtoMessage()               {}
func (*SalaryDataS2C) Descriptor() ([]byte, []int) { return fileDescriptor65, []int{3} }

func (m *SalaryDataS2C) GetBuySalaryCfgId() int32 {
	if m != nil && m.BuySalaryCfgId != nil {
		return *m.BuySalaryCfgId
	}
	return 0
}

func (m *SalaryDataS2C) GetMonthCardId() int32 {
	if m != nil && m.MonthCardId != nil {
		return *m.MonthCardId
	}
	return 0
}

func init() {
	proto.RegisterType((*Salary)(nil), "Salary")
	proto.RegisterType((*BuySalaryC2S)(nil), "BuySalaryC2S")
	proto.RegisterType((*BuySalaryS2C)(nil), "BuySalaryS2C")
	proto.RegisterType((*SalaryDataS2C)(nil), "SalaryDataS2C")
	proto.RegisterEnum("BuySalaryC2S_MsgID", BuySalaryC2S_MsgID_name, BuySalaryC2S_MsgID_value)
	proto.RegisterEnum("BuySalaryS2C_MsgID", BuySalaryS2C_MsgID_name, BuySalaryS2C_MsgID_value)
	proto.RegisterEnum("SalaryDataS2C_MsgID", SalaryDataS2C_MsgID_name, SalaryDataS2C_MsgID_value)
}

func init() { proto.RegisterFile("salary.proto", fileDescriptor65) }

var fileDescriptor65 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xcc, 0x49,
	0x2c, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x49, 0xce, 0xcf, 0xcd, 0xcd, 0xcf,
	0x83, 0xf0, 0x94, 0x4c, 0xb9, 0xd8, 0x82, 0xc1, 0xb2, 0x42, 0x62, 0x5c, 0x7c, 0x49, 0xa5, 0x95,
	0x10, 0x8e, 0x73, 0x5a, 0xba, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xab, 0x90, 0x30, 0x17,
	0x37, 0x50, 0x79, 0x49, 0x86, 0x73, 0x62, 0x51, 0x0a, 0x50, 0x90, 0x09, 0x24, 0xa8, 0x64, 0xc9,
	0xc5, 0xe3, 0x04, 0x57, 0x6c, 0x14, 0x0c, 0x52, 0x54, 0x8c, 0xae, 0x53, 0x49, 0x84, 0x8b, 0xd5,
	0xb7, 0x38, 0xdd, 0xd3, 0x45, 0x88, 0x9b, 0x8b, 0x2d, 0x15, 0xcc, 0x12, 0x68, 0xac, 0x40, 0xd1,
	0x1a, 0x6c, 0xe4, 0x4c, 0x8a, 0xd6, 0x20, 0x2e, 0x5e, 0x88, 0x3e, 0x97, 0xc4, 0x92, 0x44, 0x90,
	0x5e, 0x92, 0xdc, 0x8c, 0xc5, 0xcc, 0xa6, 0x0a, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x30,
	0x2b, 0x27, 0x1d, 0x01, 0x00, 0x00,
}
