// Code generated by protoc-gen-go.
// source: team_photo.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ActivatePieceC2S_MsgID int32

const (
	ActivatePieceC2S_eMsgID ActivatePieceC2S_MsgID = 2358
)

var ActivatePieceC2S_MsgID_name = map[int32]string{
	2358: "eMsgID",
}
var ActivatePieceC2S_MsgID_value = map[string]int32{
	"eMsgID": 2358,
}

func (x ActivatePieceC2S_MsgID) Enum() *ActivatePieceC2S_MsgID {
	p := new(ActivatePieceC2S_MsgID)
	*p = x
	return p
}
func (x ActivatePieceC2S_MsgID) String() string {
	return proto.EnumName(ActivatePieceC2S_MsgID_name, int32(x))
}
func (x *ActivatePieceC2S_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActivatePieceC2S_MsgID_value, data, "ActivatePieceC2S_MsgID")
	if err != nil {
		return err
	}
	*x = ActivatePieceC2S_MsgID(value)
	return nil
}
func (ActivatePieceC2S_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor76, []int{2, 0} }

type ActivatePieceS2C_MsgID int32

const (
	ActivatePieceS2C_eMsgID ActivatePieceS2C_MsgID = 2358
)

var ActivatePieceS2C_MsgID_name = map[int32]string{
	2358: "eMsgID",
}
var ActivatePieceS2C_MsgID_value = map[string]int32{
	"eMsgID": 2358,
}

func (x ActivatePieceS2C_MsgID) Enum() *ActivatePieceS2C_MsgID {
	p := new(ActivatePieceS2C_MsgID)
	*p = x
	return p
}
func (x ActivatePieceS2C_MsgID) String() string {
	return proto.EnumName(ActivatePieceS2C_MsgID_name, int32(x))
}
func (x *ActivatePieceS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActivatePieceS2C_MsgID_value, data, "ActivatePieceS2C_MsgID")
	if err != nil {
		return err
	}
	*x = ActivatePieceS2C_MsgID(value)
	return nil
}
func (ActivatePieceS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor76, []int{3, 0} }

type TeamPhotoListS2C_MsgID int32

const (
	TeamPhotoListS2C_eMsgID TeamPhotoListS2C_MsgID = 2359
)

var TeamPhotoListS2C_MsgID_name = map[int32]string{
	2359: "eMsgID",
}
var TeamPhotoListS2C_MsgID_value = map[string]int32{
	"eMsgID": 2359,
}

func (x TeamPhotoListS2C_MsgID) Enum() *TeamPhotoListS2C_MsgID {
	p := new(TeamPhotoListS2C_MsgID)
	*p = x
	return p
}
func (x TeamPhotoListS2C_MsgID) String() string {
	return proto.EnumName(TeamPhotoListS2C_MsgID_name, int32(x))
}
func (x *TeamPhotoListS2C_MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TeamPhotoListS2C_MsgID_value, data, "TeamPhotoListS2C_MsgID")
	if err != nil {
		return err
	}
	*x = TeamPhotoListS2C_MsgID(value)
	return nil
}
func (TeamPhotoListS2C_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor76, []int{4, 0} }

// 王朝掠影
// 单个相册数据
type OnePhoto struct {
	PhotoId          *int32 `protobuf:"varint,1,opt,name=photo_id" json:"photo_id,omitempty"`
	Area1            *bool  `protobuf:"varint,2,opt,name=area1" json:"area1,omitempty"`
	Area2            *bool  `protobuf:"varint,3,opt,name=area2" json:"area2,omitempty"`
	Area3            *bool  `protobuf:"varint,4,opt,name=area3" json:"area3,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OnePhoto) Reset()                    { *m = OnePhoto{} }
func (m *OnePhoto) String() string            { return proto.CompactTextString(m) }
func (*OnePhoto) ProtoMessage()               {}
func (*OnePhoto) Descriptor() ([]byte, []int) { return fileDescriptor76, []int{0} }

func (m *OnePhoto) GetPhotoId() int32 {
	if m != nil && m.PhotoId != nil {
		return *m.PhotoId
	}
	return 0
}

func (m *OnePhoto) GetArea1() bool {
	if m != nil && m.Area1 != nil {
		return *m.Area1
	}
	return false
}

func (m *OnePhoto) GetArea2() bool {
	if m != nil && m.Area2 != nil {
		return *m.Area2
	}
	return false
}

func (m *OnePhoto) GetArea3() bool {
	if m != nil && m.Area3 != nil {
		return *m.Area3
	}
	return false
}

// 已解锁的相册列表
type TeamPhotoData struct {
	Photos           []*OnePhoto `protobuf:"bytes,1,rep,name=photos" json:"photos,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *TeamPhotoData) Reset()                    { *m = TeamPhotoData{} }
func (m *TeamPhotoData) String() string            { return proto.CompactTextString(m) }
func (*TeamPhotoData) ProtoMessage()               {}
func (*TeamPhotoData) Descriptor() ([]byte, []int) { return fileDescriptor76, []int{1} }

func (m *TeamPhotoData) GetPhotos() []*OnePhoto {
	if m != nil {
		return m.Photos
	}
	return nil
}

// 激活相册
type ActivatePieceC2S struct {
	PhotoId          *int32 `protobuf:"varint,1,opt,name=photo_id" json:"photo_id,omitempty"`
	AreaId           *int32 `protobuf:"varint,2,opt,name=area_id" json:"area_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActivatePieceC2S) Reset()                    { *m = ActivatePieceC2S{} }
func (m *ActivatePieceC2S) String() string            { return proto.CompactTextString(m) }
func (*ActivatePieceC2S) ProtoMessage()               {}
func (*ActivatePieceC2S) Descriptor() ([]byte, []int) { return fileDescriptor76, []int{2} }

func (m *ActivatePieceC2S) GetPhotoId() int32 {
	if m != nil && m.PhotoId != nil {
		return *m.PhotoId
	}
	return 0
}

func (m *ActivatePieceC2S) GetAreaId() int32 {
	if m != nil && m.AreaId != nil {
		return *m.AreaId
	}
	return 0
}

// 返回激活相册
type ActivatePieceS2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActivatePieceS2C) Reset()                    { *m = ActivatePieceS2C{} }
func (m *ActivatePieceS2C) String() string            { return proto.CompactTextString(m) }
func (*ActivatePieceS2C) ProtoMessage()               {}
func (*ActivatePieceS2C) Descriptor() ([]byte, []int) { return fileDescriptor76, []int{3} }

// 登录下发数据
type TeamPhotoListS2C struct {
	Photos           []*OnePhoto `protobuf:"bytes,1,rep,name=photos" json:"photos,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *TeamPhotoListS2C) Reset()                    { *m = TeamPhotoListS2C{} }
func (m *TeamPhotoListS2C) String() string            { return proto.CompactTextString(m) }
func (*TeamPhotoListS2C) ProtoMessage()               {}
func (*TeamPhotoListS2C) Descriptor() ([]byte, []int) { return fileDescriptor76, []int{4} }

func (m *TeamPhotoListS2C) GetPhotos() []*OnePhoto {
	if m != nil {
		return m.Photos
	}
	return nil
}

func init() {
	proto.RegisterType((*OnePhoto)(nil), "OnePhoto")
	proto.RegisterType((*TeamPhotoData)(nil), "TeamPhotoData")
	proto.RegisterType((*ActivatePieceC2S)(nil), "ActivatePieceC2S")
	proto.RegisterType((*ActivatePieceS2C)(nil), "ActivatePieceS2C")
	proto.RegisterType((*TeamPhotoListS2C)(nil), "TeamPhotoListS2C")
	proto.RegisterEnum("ActivatePieceC2S_MsgID", ActivatePieceC2S_MsgID_name, ActivatePieceC2S_MsgID_value)
	proto.RegisterEnum("ActivatePieceS2C_MsgID", ActivatePieceS2C_MsgID_name, ActivatePieceS2C_MsgID_value)
	proto.RegisterEnum("TeamPhotoListS2C_MsgID", TeamPhotoListS2C_MsgID_name, TeamPhotoListS2C_MsgID_value)
}

func init() { proto.RegisterFile("team_photo.proto", fileDescriptor76) }

var fileDescriptor76 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x49, 0x4d, 0xcc,
	0x8d, 0x2f, 0xc8, 0xc8, 0x2f, 0xc9, 0xd7, 0x2b, 0x28, 0x02, 0x92, 0x52, 0x3c, 0xc9, 0xf9, 0xb9,
	0xb9, 0xf9, 0x79, 0x10, 0x9e, 0x92, 0x27, 0x17, 0x87, 0x7f, 0x5e, 0x6a, 0x00, 0x48, 0x5e, 0x48,
	0x80, 0x8b, 0x03, 0xac, 0x30, 0x3e, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x55, 0x88, 0x97,
	0x8b, 0x35, 0xb1, 0x28, 0x35, 0xd1, 0x50, 0x82, 0x09, 0xc8, 0xe5, 0x80, 0x71, 0x8d, 0x24, 0x98,
	0x91, 0xb9, 0xc6, 0x12, 0x2c, 0x20, 0xae, 0x92, 0x16, 0x17, 0x6f, 0x08, 0xd0, 0x32, 0xb0, 0x59,
	0x2e, 0x89, 0x25, 0x89, 0x42, 0x92, 0x5c, 0x6c, 0x60, 0xf3, 0x8a, 0x81, 0xa6, 0x31, 0x6b, 0x70,
	0x1b, 0x71, 0xea, 0xc1, 0xac, 0x52, 0xf2, 0xe6, 0x12, 0x70, 0x4c, 0x2e, 0xc9, 0x2c, 0x4b, 0x2c,
	0x49, 0x0d, 0xc8, 0x4c, 0x4d, 0x4e, 0x75, 0x36, 0x0a, 0xc6, 0x62, 0x3d, 0x3f, 0x17, 0x3b, 0xc8,
	0x02, 0x90, 0x00, 0xc8, 0x01, 0xac, 0x4a, 0x22, 0x5c, 0xac, 0xbe, 0xc5, 0xe9, 0x9e, 0x2e, 0x42,
	0xdc, 0x5c, 0x6c, 0xa9, 0x60, 0x96, 0xc0, 0x36, 0x21, 0x25, 0x0d, 0x34, 0xc3, 0x82, 0x8d, 0x9c,
	0x71, 0xa8, 0x74, 0xe6, 0x12, 0x80, 0x3b, 0xd1, 0x27, 0xb3, 0xb8, 0x04, 0xa8, 0x12, 0x9f, 0x2b,
	0xb1, 0x18, 0xb2, 0x5d, 0x08, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x86, 0x76, 0x46, 0x53, 0x01,
	0x00, 0x00,
}
